<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_404 NOT_FOUND</name>
   <tag></tag>
   <elementGuidId>c0a716c0-b352-4552-b959-c37c82326fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.error-code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='DEPLOYMENT_NOT_FOUND'])[1]/preceding::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a20135c2-a29a-41f5-aa59-5589d14d0443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error-code</value>
      <webElementGuid>b845ab84-b8b3-4a55-ac4f-f4e8b2323479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>404: NOT_FOUND</value>
      <webElementGuid>ccfc3450-6e77-4397-8f60-c159ad660f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[1]/p[@class=&quot;devinfo-container&quot;]/span[@class=&quot;error-code&quot;]</value>
      <webElementGuid>9c0561e2-1052-4a86-899d-6faba8ba17be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEPLOYMENT_NOT_FOUND'])[1]/preceding::span[1]</value>
      <webElementGuid>11e70be6-7007-4945-a6ed-e7da251efb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)=': NOT_FOUND']/parent::*</value>
      <webElementGuid>585e2c71-4e8a-45e8-ab53-0bea29168b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>4595de2e-5a2d-4da2-a9b0-8173cbc2c087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '404: NOT_FOUND' or . = '404: NOT_FOUND')]</value>
      <webElementGuid>0a737cf3-eca3-4181-b4ee-efdff1925ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
