<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Promosi Katalog MelakaKatalog Promosi</name>
   <tag></tag>
   <elementGuidId>8c06d031-cf01-47d6-a0c5-e2e407e35d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-row.items-center.justify-between.gap-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f59892b3-9f61-4964-b3c4-d30f97f8957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-row items-center justify-between gap-2</value>
      <webElementGuid>8f772440-07c4-40e5-99c4-2c3ff7f393cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promosi Katalog MelakaKatalog Promosi</value>
      <webElementGuid>4fdcb7ba-83c3-4357-bdc0-1e54fac30381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-row items-center justify-between gap-2&quot;]</value>
      <webElementGuid>16a3fdd3-109d-4ec1-af21-84e9099b6fac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]/div</value>
      <webElementGuid>8bb58bc9-22d3-4cb1-9dec-55f2ccecc023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::div[12]</value>
      <webElementGuid>e015538c-624b-4305-9927-b94cd2d5d47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::div[13]</value>
      <webElementGuid>6440f03a-768b-4b16-a627-467a89a48bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div</value>
      <webElementGuid>12f38cf9-c418-417e-8f4b-16531b617804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Promosi Katalog MelakaKatalog Promosi' or . = 'Promosi Katalog MelakaKatalog Promosi')]</value>
      <webElementGuid>83c14f0a-1897-489e-b5f8-6dc26b4e89d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
