<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Total produk0Total stok keseluruhan0Pro_50f292</name>
   <tag></tag>
   <elementGuidId>0dbe58d7-85d9-49f3-aca3-3eae83599c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>363e264d-4f96-4325-85c6-c259c3406844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-neutral-N0 rounded-xl p-6 grid grid-cols-2 gap-5 py-4 md:grid-cols-12</value>
      <webElementGuid>9077f05a-99d7-4aa4-978c-b0c7ea77b68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total produk0Total stok keseluruhan0Produk habis0Produk mau habis0Lihat Pergerakan Stok</value>
      <webElementGuid>1b190cc1-0567-47cb-9035-904fff6cd38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[@class=&quot;flex-col gap-4 flex&quot;]/div[@class=&quot;bg-neutral-N0 rounded-xl p-6 grid grid-cols-2 gap-5 py-4 md:grid-cols-12&quot;]</value>
      <webElementGuid>e3b33263-1a53-454b-865f-cd3cc5a2c328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]/div</value>
      <webElementGuid>fadbc111-a6e3-40f6-a47a-591d17f9fcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok Inventori'])[3]/following::div[2]</value>
      <webElementGuid>7d28932c-0cd6-45bd-951c-2aed3932d340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stok Inventori'])[2]/following::div[2]</value>
      <webElementGuid>82251ceb-0fe5-4c3e-ac42-90728d7f11ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div</value>
      <webElementGuid>13c2d52f-16ba-4d12-b9b5-fcf09c3d7bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Total produk0Total stok keseluruhan0Produk habis0Produk mau habis0Lihat Pergerakan Stok' or . = 'Total produk0Total stok keseluruhan0Produk habis0Produk mau habis0Lihat Pergerakan Stok')]</value>
      <webElementGuid>1c60eabf-dd69-412e-809f-72f2258fc877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
