<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Punya banyak toko di banyak marketplace_1a7ca3</name>
   <tag></tag>
   <elementGuidId>899381ba-0784-4096-b23c-5fe46a45bc14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.h1.he.h1-mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketplace-integration']/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f27c492-4d63-44b2-bb0c-5c18034c6fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text__marketplace-integration-content</value>
      <webElementGuid>2029ecc2-3890-4bc9-b766-5fe7e8fe60dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1 he h1-mobile</value>
      <webElementGuid>dd315ac5-2ffe-4eae-aa33-994a16da53e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Punya banyak toko di banyak marketplace? Koneksikan aja dulu</value>
      <webElementGuid>6cb47cf6-ae31-4a41-98f5-3cf0df720d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-integration&quot;)/div[@class=&quot;flex-feature-texts&quot;]/div[@class=&quot;h1 he h1-mobile&quot;]</value>
      <webElementGuid>d5dba408-ed11-4595-9da1-f816fffd9bc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketplace-integration']/div[2]/div[2]</value>
      <webElementGuid>9cdc9471-6167-461c-9aa1-deb18bd637d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INTEGRASI ANTAR MARKETPLACE'])[1]/following::div[1]</value>
      <webElementGuid>b36847dd-d33b-4a02-b32f-9c33c6275eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELENGKAPNYA'])[3]/following::div[6]</value>
      <webElementGuid>ca385c00-d721-404a-9949-bb7a280418dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[1]/preceding::div[2]</value>
      <webElementGuid>d11980a0-91e7-40e2-acaf-81bdde739651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Punya banyak toko di']/parent::*</value>
      <webElementGuid>060a26e7-93da-40fa-a839-128ba9a900f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]</value>
      <webElementGuid>db95f618-3eb8-4dae-bfb5-532f6c265b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Punya banyak toko di banyak marketplace? Koneksikan aja dulu' or . = 'Punya banyak toko di banyak marketplace? Koneksikan aja dulu')]</value>
      <webElementGuid>4a8b14b9-9999-42a9-af45-8647a6de5c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
