<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Atur inventori dan pesanan toko online-_6acacf</name>
   <tag></tag>
   <elementGuidId>45a16b67-c11b-48c8-8564-ecdc3650186a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#store-management > div.flex-feature-texts > div.h1.he.h1-mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store-management']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5df2620-403b-4c8c-aa6c-eb5cf9f3ecb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text__store-management-content</value>
      <webElementGuid>2595adde-cdde-4715-8f3b-b085222151d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1 he h1-mobile</value>
      <webElementGuid>459cf7ea-b045-43a4-9928-619755362b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atur inventori dan pesanan toko online-mu dengan mudah dan terpusat</value>
      <webElementGuid>605625a8-c67a-4c49-8ecc-45c89098b8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-management&quot;)/div[@class=&quot;flex-feature-texts&quot;]/div[@class=&quot;h1 he h1-mobile&quot;]</value>
      <webElementGuid>ba461389-62e1-4392-8be1-fb653c8a56fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store-management']/div/div[2]</value>
      <webElementGuid>1fa267cf-ddc0-44bc-95a8-417e2e742470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANAJEMEN INVENTORI DAN ORDER'])[1]/following::div[1]</value>
      <webElementGuid>53ced58b-a773-4af9-9ee0-6ab2b8887907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[1]/following::div[4]</value>
      <webElementGuid>d152f7d2-e714-4a47-9c08-3160d08d42ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Atur']/parent::*</value>
      <webElementGuid>b0cbf85a-4ec1-4e62-ad20-c02eb3725855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]</value>
      <webElementGuid>d705ab7c-0598-41f1-8e49-69fc59d529bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Atur inventori dan pesanan toko online-mu dengan mudah dan terpusat' or . = 'Atur inventori dan pesanan toko online-mu dengan mudah dan terpusat')]</value>
      <webElementGuid>92d443e4-6d71-48a4-85db-393006e60c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
