<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INTEGRASI ANTAR MARKETPLACE</name>
   <tag></tag>
   <elementGuidId>c0e1dba4-15b3-488b-9a75-ecdb582f7eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.b2.le.margin-bot-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketplace-integration']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5fffc87-7fe0-41d3-be73-a7ad95e0c5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text__marketplace-integration-title</value>
      <webElementGuid>21e53827-05de-4189-9ef2-d8862ed0f3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b2 le margin-bot-12</value>
      <webElementGuid>cef2ff14-cecb-4c3b-a887-25eb863a8cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INTEGRASI ANTAR MARKETPLACE</value>
      <webElementGuid>2c5fb0f0-8021-4cfd-9ce2-6794b678ac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-integration&quot;)/div[@class=&quot;flex-feature-texts&quot;]/div[@class=&quot;b2 le margin-bot-12&quot;]</value>
      <webElementGuid>00547a07-58bd-4d39-a91c-9d630f2f519d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketplace-integration']/div[2]/div</value>
      <webElementGuid>3a7fa1b7-7814-4be3-b027-151b836334a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELENGKAPNYA'])[3]/following::div[5]</value>
      <webElementGuid>898c42b0-9b42-49c7-bafb-4d4b136931c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::div[7]</value>
      <webElementGuid>dcce9348-da64-4397-b430-6699ec0dd228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='banyak marketplace'])[1]/preceding::div[1]</value>
      <webElementGuid>6707c82c-2324-4e1c-a97a-b7be0c353ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INTEGRASI ANTAR MARKETPLACE']/parent::*</value>
      <webElementGuid>2f5c6e62-bf6c-4c0f-97a2-80fc4f599846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div</value>
      <webElementGuid>65136afe-34a0-49a4-af75-abd83eefa6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'INTEGRASI ANTAR MARKETPLACE' or . = 'INTEGRASI ANTAR MARKETPLACE')]</value>
      <webElementGuid>f711eb3f-71c6-43f0-ad91-66c702edaa85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
