<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kelola hasil penjualan di semua bisnis _2f0e4e</name>
   <tag></tag>
   <elementGuidId>f2431cf6-8482-446c-8927-432081547bb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accounting > div.flex-feature-texts > div.h1.he.h1-mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accounting']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb2d01c5-7c24-492c-8d5c-1adc3f2f4abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text__accounting-content</value>
      <webElementGuid>2b9178da-932e-4df9-9735-97bd1c9a82da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1 he h1-mobile</value>
      <webElementGuid>44ed0e46-927a-4ce2-80d3-20f5875a3086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelola hasil penjualan di semua bisnis online dan toko kamu dengan mudah</value>
      <webElementGuid>a76d3c16-c9ad-4a46-9870-939991eec8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accounting&quot;)/div[@class=&quot;flex-feature-texts&quot;]/div[@class=&quot;h1 he h1-mobile&quot;]</value>
      <webElementGuid>33a373b0-d8ef-4194-9541-7e15d2725bf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accounting']/div/div[2]</value>
      <webElementGuid>f8a4c6cf-34fd-44fb-b913-b8cb41a2c3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATATAN KEUANGAN'])[1]/following::div[1]</value>
      <webElementGuid>49f61b44-8ddb-4509-804f-eb353475ae9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[3]/following::div[4]</value>
      <webElementGuid>343670fd-49be-4f67-97ab-6f75369d933d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[4]/preceding::div[2]</value>
      <webElementGuid>29cdf771-a9d3-4c76-8f66-fee741de9033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelola']/parent::*</value>
      <webElementGuid>e3207a8d-a6d4-460a-b5ad-42ed4b932935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div[2]</value>
      <webElementGuid>d0d611be-ab0f-4df7-8da3-d756e973e906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kelola hasil penjualan di semua bisnis online dan toko kamu dengan mudah' or . = 'Kelola hasil penjualan di semua bisnis online dan toko kamu dengan mudah')]</value>
      <webElementGuid>dec7d3dd-b16a-4ccd-8f8d-98cd12da3724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
