<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Info Tipe BisnisDistributor yang menjua_5e6de4</name>
   <tag></tag>
   <elementGuidId>bc7c1425-191f-41d5-8e75-2e1e46959dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-popover-panel-:r2:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0720d897-5051-487e-89ea-b65a9c27c8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-neutral-N700 z-10 inline-flex max-w-7xl items-center justify-center rounded px-3 py-2 opacity-100</value>
      <webElementGuid>4cb9165b-e551-450d-9b0a-df931a241654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__tooltip__business-type-tooltip__tooltip__message</value>
      <webElementGuid>66d2b91a-89fa-496f-a2e7-4c8b4cd4377c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-popover-panel-:r2:</value>
      <webElementGuid>85ceffa3-a429-456b-9229-a256d6ecbe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cad6049c-6e29-48c6-9eff-30919629ae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>72bf903a-367d-47e9-9abf-c6a953b4b4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popper-reference-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>621855bd-cc8f-4a4b-b372-d42635076d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popper-escaped</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>420a7528-5f94-4eb1-a302-737ffda11212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popper-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>895b7f67-dd35-4309-9cce-2b66b1979547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info Tipe Bisnis:Distributor yang menjual produk dari pabrik ke toko atau langsung ke pembeli.Toko retail adalah tempat yang menjual barang atau jasa kepada pembeli.Brand adalah entitas yang memiliki merek sendiri dalam menjalankan bisnisnya.Penjual Online adalah pihak yang menjual barang atau jasa di internet.</value>
      <webElementGuid>4a1aa38f-5edf-4de3-b0c8-49df2b06b0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-panel-:r2:&quot;)</value>
      <webElementGuid>b8f6b656-f612-49d3-b688-8a56c60a3149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-popover-panel-:r2:']</value>
      <webElementGuid>61bf96f6-ba2a-49ee-80b4-1333c5bd1a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[4]/div/div/div</value>
      <webElementGuid>17105a3e-9e60-4cbd-8190-693d75d416b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Bisnis'])[1]/following::div[2]</value>
      <webElementGuid>30b74d49-c23d-4c51-9038-dae2fd701833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Bisnis Kamu'])[1]/following::div[5]</value>
      <webElementGuid>9ed862ed-776f-470a-81f8-6c221c609200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>40361ea4-f4f6-4fc1-b7c6-eac11654ae0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-popover-panel-:r2:' and (text() = 'Info Tipe Bisnis:Distributor yang menjual produk dari pabrik ke toko atau langsung ke pembeli.Toko retail adalah tempat yang menjual barang atau jasa kepada pembeli.Brand adalah entitas yang memiliki merek sendiri dalam menjalankan bisnisnya.Penjual Online adalah pihak yang menjual barang atau jasa di internet.' or . = 'Info Tipe Bisnis:Distributor yang menjual produk dari pabrik ke toko atau langsung ke pembeli.Toko retail adalah tempat yang menjual barang atau jasa kepada pembeli.Brand adalah entitas yang memiliki merek sendiri dalam menjalankan bisnisnya.Penjual Online adalah pihak yang menjual barang atau jasa di internet.')]</value>
      <webElementGuid>1cb73972-8b11-4edb-b38c-d62ea92a00a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
