<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brand_businessType</name>
   <tag></tag>
   <elementGuidId>9cf6be4c-c68d-4636-92a1-d478bcd14e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='online_seller-:Ri96l6:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aeec905-3147-4806-8564-5693ebb0b5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b3b32e76-9577-40e3-bb2a-d52b96ad74fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>ff3b84bf-ab72-420c-94b8-97dac60aa32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>online_seller-:Ri96l6:</value>
      <webElementGuid>989f8054-c924-4ab3-bcc2-c78eeb8f4c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-neutral-N400 enabled:checked:text-blue-B700 h-4 w-4 border-2 enabled:focus:ring-0 enabled:focus:ring-offset-0 disabled:bg-neutral-N100 disabled:cursor-not-allowed checked:disabled:bg-blue-B400 checked:disabled:hover:bg-blue-B400</value>
      <webElementGuid>95ed05af-5c3e-409f-a667-2b80759c8d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__radio-button__penjual-online</value>
      <webElementGuid>b3d746b5-954a-4cf1-9bd5-f2ccdf737eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>online_seller</value>
      <webElementGuid>bebcacb6-1b35-4f18-b71e-faaf0dc07403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;online_seller-:Ri96l6:&quot;)</value>
      <webElementGuid>46e7ca46-66e5-4e0a-9256-8ea2d0939496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='online_seller-:Ri96l6:']</value>
      <webElementGuid>300aad5f-b9ed-4c6d-a29a-4c346a11823c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[4]/div[2]/div[4]/input</value>
      <webElementGuid>89ccc379-9d3a-43b2-83f0-7f7a650805e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d09ae2b0-7be4-424b-9973-f07a52a8fc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'businessType' and @id = 'online_seller-:Ri96l6:']</value>
      <webElementGuid>0b8ee89b-4af3-4b44-8bc4-08a645789aed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
