<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selamat Datang diMelaka_name</name>
   <tag></tag>
   <elementGuidId>011b4e6e-e7ea-4f9f-ade9-91bdee901817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-:R36l6:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03aeca2e-8477-4903-a654-7ef05443bca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4b4f6bb-c817-4a4b-92dd-4a44877bc45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>8e8e1d20-8566-4ec5-9b7b-fd65c50ee50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>584d40a6-f5ab-44b1-bccc-e80f63d4cb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-:R36l6:</value>
      <webElementGuid>663339e7-3574-497f-84d5-6e777f4947b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>43bb4318-b86f-49dc-95de-b5e46582916a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-disabled border-neutral-N300 enabled:text-he peer block w-full rounded border p-4 text-base leading-6 placeholder-transparent enabled:focus:outline-none enabled:focus:ring-1 enabled:focus:border-blue-B700 enabled:focus:ring-blue-B700</value>
      <webElementGuid>e0eee0de-7918-4691-9e15-3358896f5202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ffaa44f9-2007-4d19-beda-f81a292bb055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__text-field__name</value>
      <webElementGuid>3ceee298-affd-4136-bb3c-5123aa7c66cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-:R36l6:&quot;)</value>
      <webElementGuid>845d6b07-e6c4-4efd-8873-9e01733af70b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-:R36l6:']</value>
      <webElementGuid>40626098-48cb-4f90-baf8-a5522cbf43c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div/div/input</value>
      <webElementGuid>bbd22c24-46bf-40f6-a6e3-c3eef35c19ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f69ad5b7-7edf-4f33-8afb-1f15a4502f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @id = 'input-:R36l6:' and @placeholder = 'placeholder']</value>
      <webElementGuid>bf2213c0-4c1b-435e-ad8e-9134fefcd8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
