<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Distributor_businessType</name>
   <tag></tag>
   <elementGuidId>46e61dfc-4c31-4e78-9b0b-cf0faf158320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retail_store-:Ra96l6:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee491134-433f-4bf1-9f11-8bcc4381ce16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>740714aa-4b6c-4064-8523-835c2a6e015f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>e4691343-c0c4-4da3-88c4-d3fadb2648b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retail_store-:Ra96l6:</value>
      <webElementGuid>329cb295-552d-4c0d-bf28-7c883100a2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-neutral-N400 enabled:checked:text-blue-B700 h-4 w-4 border-2 enabled:focus:ring-0 enabled:focus:ring-offset-0 disabled:bg-neutral-N100 disabled:cursor-not-allowed checked:disabled:bg-blue-B400 checked:disabled:hover:bg-blue-B400</value>
      <webElementGuid>11056ef1-b45c-4b8b-b45b-3a1973632294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__radio-button__toko-retail</value>
      <webElementGuid>0b988a8e-dd32-40fe-a1c0-dc15216f0043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>retail_store</value>
      <webElementGuid>1a37dfa2-1ebf-4b8e-a674-4eb6db888f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retail_store-:Ra96l6:&quot;)</value>
      <webElementGuid>54b79a84-35eb-4e5d-ac0e-e31b5651f25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retail_store-:Ra96l6:']</value>
      <webElementGuid>284c44da-68f4-4f62-bad1-c563390f2d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>a7866037-cb9d-410d-9509-c3f380c36889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>db8ff292-c7cf-4e56-8dfd-14ca660af29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'businessType' and @id = 'retail_store-:Ra96l6:']</value>
      <webElementGuid>4836eea4-35b1-4965-b7eb-1a8e78f9cbfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
