<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Kata Sandi_isTncChecked</name>
   <tag></tag>
   <elementGuidId>6c272673-d00b-4db5-9e89-2cd4c2e08999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register__checkbox__tnc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register__checkbox__tnc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58348163-33cd-4414-ab1c-50869d97321a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>51f6ddde-f589-4a06-86e9-1ff49fe806cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>83183f0f-44bb-4c4d-949d-338e3a481055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isTncChecked</value>
      <webElementGuid>3cec24fd-ee7d-4606-a010-1bb78f13477f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a9c0281a-825d-4081-8ad1-99a09e6d3162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-blue-B700 border-neutral-N400 h-5 w-5 cursor-pointer rounded border-2 focus:outline-0 focus:ring-transparent disabled:text-neutral-N200 disabled:border-neutral-N200 disabled:cursor-not-allowed checked:disabled:text-blue-B400 checked:disabled:border-blue-B400 indeterminate:disabled:text-blue-B400 indeterminate:disabled:border-blue-B400</value>
      <webElementGuid>f2bc5aeb-e4af-4290-bc67-5b637892b516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>d483929f-6ad3-4780-b820-ece32095b360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d9331b26-3561-4154-9209-d8d5c094eedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register__checkbox__tnc&quot;)</value>
      <webElementGuid>b94606de-a41a-4478-b9c7-e43c8383ac18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register__checkbox__tnc']</value>
      <webElementGuid>43d1316f-a63e-4c3a-949a-7955ca2fae7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[8]/div/input</value>
      <webElementGuid>9ccfddd7-a992-4d25-93a1-f38da1b15e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>2343f40a-1ab5-4609-9c33-8c02d4cd01eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register__checkbox__tnc' and @name = 'isTncChecked' and @type = 'checkbox']</value>
      <webElementGuid>a742acc2-1552-4f6e-b70a-336986247f38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
