<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_masuk</name>
   <tag></tag>
   <elementGuidId>f70d2882-ac03-475e-8e0f-568a86594815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbarlogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'masuk')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27d8d282-2d95-4b65-a44d-bc5ad57e0216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>analytics</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>202d9f98-7a44-457e-ace3-bd9b60bc444d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing__button__login</value>
      <webElementGuid>f3200800-1046-48c3-999f-49a4ace7be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>button-app</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>e7ce61b5-30a6-4f27-848d-023c452b99ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dashboard.melaka.app/login</value>
      <webElementGuid>44b61e9f-9d97-411c-8004-9f58ae5b3651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbarlogin</value>
      <webElementGuid>265c03c5-3ad9-4e50-bde3-6835d96ff461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>masuk</value>
      <webElementGuid>26c6407c-888d-4475-9dff-810a15acd53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js w-mod-ix wf-nunito-n2-active wf-nunito-n5-active wf-nunito-n3-active wf-nunito-n9-active wf-nunito-n8-active wf-nunito-n4-active wf-nunito-n6-active wf-nunito-n7-active wf-nunito-i3-active wf-nunito-i4-active wf-nunito-i8-active wf-nunito-i7-active wf-nunito-i9-active wf-nunito-i6-active wf-nunito-i5-active wf-nunito-i2-active wf-active&quot;]/body[1]/aside[@class=&quot;navbar&quot;]/div[@class=&quot;navbarleft-container shadow-three w-nav&quot;]/div[@class=&quot;container-5&quot;]/div[@class=&quot;navbar-wrapper-3&quot;]/nav[@class=&quot;menuwrapper w-nav-menu&quot;]/ul[@class=&quot;navmenu w-list-unstyled&quot;]/li[@class=&quot;rightmenu&quot;]/a[@class=&quot;navbarlogin&quot;]</value>
      <webElementGuid>dd71d557-6ef1-44ba-8f66-46804f5b7c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'masuk')]</value>
      <webElementGuid>72fbc5ec-2440-489b-a915-e3823d5724fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Bantuan'])[1]/following::a[1]</value>
      <webElementGuid>287f0728-ef8b-445c-8ed0-a1ce39f111cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seller Academy'])[1]/following::a[2]</value>
      <webElementGuid>00e77e10-ff7c-4567-a85b-0f98ebd0bbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hubungi kami'])[1]/preceding::a[1]</value>
      <webElementGuid>a7b4359f-6263-472d-9d52-5a6e75dd015b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='masuk']/parent::*</value>
      <webElementGuid>5f8e20bd-1116-4728-b8cb-1ca170f168ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dashboard.melaka.app/login')]</value>
      <webElementGuid>92a2a889-08f8-433d-9778-262aa68fe6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>f52b7825-5da2-4303-b30c-c663e546b10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dashboard.melaka.app/login' and (text() = 'masuk' or . = 'masuk')]</value>
      <webElementGuid>438c101e-9051-4a40-a38e-c4cf75c203b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
