<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pelajari Lebih Lanjut</name>
   <tag></tag>
   <elementGuidId>1eaf873f-a098-4e32-aa45-696fdcd13278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link-block.w-inline-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketplace-integration']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6f1475e-d09a-4a3f-9e65-ddd63348bb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>analytics</name>
      <type>Main</type>
      <value>learn_more</value>
      <webElementGuid>3ac24c4b-cc92-4c3d-b3f6-e97b78900c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text-link__marketplace-integration-more</value>
      <webElementGuid>0725b73b-977f-418a-b846-a80e8933571f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.melaka.app/help-center</value>
      <webElementGuid>26126bfe-784f-44ad-a30f-8565e6d740bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>64348754-4e38-40cb-bd11-912c9d5bba34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-block w-inline-block</value>
      <webElementGuid>1bda32a8-8f04-4b37-b916-1f0bfc432846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelajari Lebih Lanjut</value>
      <webElementGuid>91800479-ebb6-435d-8453-ae84218d72c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-integration&quot;)/div[@class=&quot;flex-feature-texts&quot;]/a[@class=&quot;link-block w-inline-block&quot;]</value>
      <webElementGuid>1ed69341-bf05-4bcf-bc3c-915660194c65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketplace-integration']/div[2]/a</value>
      <webElementGuid>f56194b9-995b-4a5d-908a-939ff0e063c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='banyak marketplace'])[1]/following::a[1]</value>
      <webElementGuid>2a8ff76f-1fc2-4e9d-8548-ef819b6da750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANAJEMEN INVENTORI DAN ORDER'])[1]/preceding::a[1]</value>
      <webElementGuid>bd8f7550-770a-495d-8936-b2af37ac56bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.melaka.app/help-center')]</value>
      <webElementGuid>5ea391e7-3633-4210-9301-abe0bace2e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a</value>
      <webElementGuid>75aeb200-f34b-4db5-bd7b-273ea4baa505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.melaka.app/help-center' and (text() = 'Pelajari Lebih Lanjut' or . = 'Pelajari Lebih Lanjut')]</value>
      <webElementGuid>e6f258b2-d32c-416a-8e52-100191675ed2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
