<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SELENGKAPNYA</name>
   <tag></tag>
   <elementGuidId>ddbfdcd3-7315-44a1-b50e-142b4409829e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button-secondary-enabled-2.w-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='melaka-solution']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1808b1ce-91ee-4b35-a3b9-79eac0ea8beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#marketplace-integration</value>
      <webElementGuid>910364b7-6cd0-47e2-9208-dc7f8c32e14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-secondary-enabled-2 w-button</value>
      <webElementGuid>c093fbf5-a158-4a9a-8a17-3eaf5fff5514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELENGKAPNYA</value>
      <webElementGuid>fd65b417-a0ec-4cc0-a42a-1d02c3fea8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;melaka-solution&quot;)/div[@class=&quot;w-layout-vflex flex-block-17&quot;]/div[@class=&quot;w-layout-hflex flex-block-49&quot;]/div[@class=&quot;w-layout-hflex flex-block-16&quot;]/div[@class=&quot;business-type---card image-1&quot;]/a[@class=&quot;button-secondary-enabled-2 w-button&quot;]</value>
      <webElementGuid>16f819a5-1c09-46de-974a-48ebc50f896d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='melaka-solution']/div/div/div/div/a</value>
      <webElementGuid>bfd04354-ccbd-4bf3-86fe-3af437f7714b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SELENGKAPNYA')]</value>
      <webElementGuid>0868ba0b-30f2-4906-a79f-9fd842a944b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjual Online'])[1]/following::a[1]</value>
      <webElementGuid>3ca2ef75-3ca9-4ac7-b4ea-fbb8859cf80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solusi Khusus'])[1]/following::a[1]</value>
      <webElementGuid>6956b6e4-c57b-48f5-b891-1f0e463ef882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko Retail'])[1]/preceding::a[1]</value>
      <webElementGuid>730751fd-22cd-43a6-9b20-bcfdbc3f26be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELENGKAPNYA'])[2]/preceding::a[1]</value>
      <webElementGuid>700a1930-c9c0-42e7-8daf-9f30a38adea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SELENGKAPNYA']/parent::*</value>
      <webElementGuid>09c67c27-3054-44d8-8e45-792d91a07053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#marketplace-integration')])[2]</value>
      <webElementGuid>8dae630a-0be8-4627-94e9-4196d2dbd5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>2b7b5fc7-adff-45c6-aee3-1fc6e621e1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#marketplace-integration' and (text() = 'SELENGKAPNYA' or . = 'SELENGKAPNYA')]</value>
      <webElementGuid>6c2e0224-2810-4253-9d0b-d5ea0bb97be1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
