<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Direktorat Jenderal Perlindungan Konsum_fe5647</name>
   <tag></tag>
   <elementGuidId>3f1c1ee3-218c-4b0a-959d-0e6e599184bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73f8760c-d7f6-495c-b583-b59f4ca79d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f</value>
      <webElementGuid>6aa93866-c3ab-444b-90ce-82688cec7fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-layout-cell</value>
      <webElementGuid>9dff6aee-91fb-4d74-89f8-89e8ce5d298d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direktorat Jenderal Perlindungan Konsumen dan Tertib Niaga Kementerian Perdagangan Republik Indonesia+62 853 1111 1010</value>
      <webElementGuid>63e92a08-ec46-42bc-9ae7-ccfbe943697d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f&quot;)</value>
      <webElementGuid>93249663-ac98-434e-a131-d8aa05c0d6bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f']</value>
      <webElementGuid>dc1e0055-7049-460a-a142-2048ffe09a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88342-c9e8833f']/div[3]</value>
      <webElementGuid>fe4ab444-555f-4236-bdae-1c5d84164681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='help@melaka.app'])[1]/following::div[1]</value>
      <webElementGuid>22319d1d-40b9-49ab-833b-0d42b68062bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(PT Melaka Commerce Technologies)'])[1]/following::div[3]</value>
      <webElementGuid>5be8bb58-38b8-4410-8b5f-3831462f1a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terdaftar di'])[1]/preceding::div[4]</value>
      <webElementGuid>d45e8a5c-a11d-4bed-82d4-54e303e7aeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solusi Kami'])[1]/preceding::div[6]</value>
      <webElementGuid>785dbffa-7cd5-4980-a50c-1c943616b7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]</value>
      <webElementGuid>267961c9-0de6-452f-844a-65fa9418e1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f' and (text() = 'Direktorat Jenderal Perlindungan Konsumen dan Tertib Niaga Kementerian Perdagangan Republik Indonesia+62 853 1111 1010' or . = 'Direktorat Jenderal Perlindungan Konsumen dan Tertib Niaga Kementerian Perdagangan Republik Indonesia+62 853 1111 1010')]</value>
      <webElementGuid>6925799b-a8bc-47fa-9ecb-c803c49b7818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
