<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Layanan Pengaduan Konsumen dan Masyarak_3905fa</name>
   <tag></tag>
   <elementGuidId>76bc606f-56b0-43c6-9040-e5218aba8350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9664e78-b3fc-42d9-acdb-9abf925bf5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f</value>
      <webElementGuid>b51cb9bd-918c-406c-93e6-35a4c2d458cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-layout-cell cell-13</value>
      <webElementGuid>20eea3f6-6ce2-47c8-a552-d408d5eaa490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Layanan Pengaduan Konsumen dan Masyarakat(PT Melaka Commerce Technologies)help@melaka.app</value>
      <webElementGuid>d7ad8f1b-e9b8-4b38-8883-43848845d1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f&quot;)</value>
      <webElementGuid>68c97a60-f763-4deb-b6ee-0d49ee9ac177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f']</value>
      <webElementGuid>68eae1f3-5557-4f67-ad03-61a361a80333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88342-c9e8833f']/div[2]</value>
      <webElementGuid>3670bff9-1a52-41b8-b566-5ed8d2532fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/following::div[6]</value>
      <webElementGuid>46841027-0223-4416-a2e2-a22aaf5e4e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Praktis dan Gratis'])[1]/following::div[8]</value>
      <webElementGuid>be94e0d7-673b-490d-83ae-e0c3d97b1591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]</value>
      <webElementGuid>cd09f946-5190-4815-8104-81dd377cd3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f' and (text() = 'Layanan Pengaduan Konsumen dan Masyarakat(PT Melaka Commerce Technologies)help@melaka.app' or . = 'Layanan Pengaduan Konsumen dan Masyarakat(PT Melaka Commerce Technologies)help@melaka.app')]</value>
      <webElementGuid>a0a21dda-dc38-45e9-b766-b4627cdcc96c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
