<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INTEGRASI ANTAR MARKETPLACEPunya banyak_458566</name>
   <tag></tag>
   <elementGuidId>9adc479e-115f-4098-9d23-63cdd9c87e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#marketplace-integration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketplace-integration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0398770-3a26-4b95-a714-743bf4a0d306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marketplace-integration</value>
      <webElementGuid>cf70bb08-140f-4151-9a93-87c40a20f7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-feature</value>
      <webElementGuid>4aa1ad24-8289-4c49-bf6d-7baa3a1b66e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INTEGRASI ANTAR MARKETPLACEPunya banyak toko di banyak marketplace? Koneksikan aja duluDengan Melaka, kamu dapat memusatkan seluruh manajemen toko online-mu di berbagai marketplace hanya di satu platform saja.Pelajari Lebih Lanjut</value>
      <webElementGuid>05246e51-56a3-4f45-b395-775592773886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-integration&quot;)</value>
      <webElementGuid>4c64e67e-0feb-442c-a933-36ea0a7f378a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='marketplace-integration']</value>
      <webElementGuid>47848da5-c465-42fd-87b3-fc5c19503449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELENGKAPNYA'])[3]/following::div[2]</value>
      <webElementGuid>74ada0af-8203-45d2-bb8e-dc42eae71a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::div[4]</value>
      <webElementGuid>dd8cd380-e445-41a6-8e7d-058c0a7cd752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>34f1bf83-0859-4d4d-8597-5145f0a489a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'marketplace-integration' and (text() = 'INTEGRASI ANTAR MARKETPLACEPunya banyak toko di banyak marketplace? Koneksikan aja duluDengan Melaka, kamu dapat memusatkan seluruh manajemen toko online-mu di berbagai marketplace hanya di satu platform saja.Pelajari Lebih Lanjut' or . = 'INTEGRASI ANTAR MARKETPLACEPunya banyak toko di banyak marketplace? Koneksikan aja duluDengan Melaka, kamu dapat memusatkan seluruh manajemen toko online-mu di berbagai marketplace hanya di satu platform saja.Pelajari Lebih Lanjut')]</value>
      <webElementGuid>2b759eef-0ca8-4c36-b8c1-b2729cc4cc4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
