<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MANAJEMEN INVENTORI DAN ORDERAtur inven_23f353</name>
   <tag></tag>
   <elementGuidId>df8c26f1-4bf0-4544-ab3f-00d52bb0184b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#store-management</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store-management']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6020ef31-4dc1-458e-9dfb-b4766b8333a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>store-management</value>
      <webElementGuid>fb376e6b-0958-4969-966f-1e78a4555458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-feature</value>
      <webElementGuid>67ecf301-a3df-41bf-a5f1-6b3df69cdb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut</value>
      <webElementGuid>6de6bf85-66bf-4837-a279-21753688ab4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-management&quot;)</value>
      <webElementGuid>16d35c1d-ca81-4b1d-8c62-a15e13e07102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='store-management']</value>
      <webElementGuid>3e9a3969-a4e4-471d-aab5-bdd705b6628b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[1]/following::div[1]</value>
      <webElementGuid>ce80e391-ca63-4001-92b5-567cddd276af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='banyak marketplace'])[1]/following::div[3]</value>
      <webElementGuid>099d7147-0c79-44f7-a4c1-cbb718be0c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>9cce8187-3bcb-4410-a195-04a68c101052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'store-management' and (text() = 'MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut' or . = 'MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut')]</value>
      <webElementGuid>0e04f692-521c-4624-ac65-a8758d196a84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
