<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Solusi Khusus untuk Setiap Tipe BisnisP_06e3b2</name>
   <tag></tag>
   <elementGuidId>8278a620-c8c1-4e5b-a70d-fef75d9280ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-layout-vflex.flex-block-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='melaka-solution']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4eb8920c-0d18-4d2c-a0e6-0db2c7302ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-layout-vflex flex-block-17</value>
      <webElementGuid>0492dd1c-acfe-43b1-a094-06d90b7ec8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solusi Khusus untuk Setiap Tipe BisnisPercayakan operasional bisnis kamu dengan fitur-fitur yang menyesuaikan kebutuhan kamu dari Melaka ✨Penjual OnlineKelola berbagai toko marketplace kamu dari satu tempat dengan memanfaatkan fitur-fitur unggulan dari MelakaSELENGKAPNYAToko RetailTingkatkan efektivitas operasional bisnis dan penjualan di toko retail kamu menggunakan fitur Kasir, Catatan Keuangan, Promosi, dan lainnya yang dibuat khusus untuk toko retail di Melaka.SELENGKAPNYABrandKembangkan kebutuhan Brand dalam memantau keinginan pasar, menjaga harga di pasaran, serta analisis penjualan online menggunakan fitur yang dibuat khusus untuk para Brand di Melaka.SELENGKAPNYA</value>
      <webElementGuid>521cc673-c569-48f4-9762-29397232568b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;melaka-solution&quot;)/div[@class=&quot;w-layout-vflex flex-block-17&quot;]</value>
      <webElementGuid>c4e752d0-2254-4362-8166-400a1de9bc1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='melaka-solution']/div</value>
      <webElementGuid>85d39ad5-0de3-42bf-8949-e1f1bccc98ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Selengkapnya'])[1]/following::div[4]</value>
      <webElementGuid>ef98b33c-9777-41dd-a407-78b8070411bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MULAI GUNAKAN, GRATIS!'])[1]/following::div[5]</value>
      <webElementGuid>43233d6f-34d7-4ab3-b92c-f9df3f54e4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>596563b8-361b-474e-883d-5b83902a2b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Solusi Khusus untuk Setiap Tipe BisnisPercayakan operasional bisnis kamu dengan fitur-fitur yang menyesuaikan kebutuhan kamu dari Melaka ✨Penjual OnlineKelola berbagai toko marketplace kamu dari satu tempat dengan memanfaatkan fitur-fitur unggulan dari MelakaSELENGKAPNYAToko RetailTingkatkan efektivitas operasional bisnis dan penjualan di toko retail kamu menggunakan fitur Kasir, Catatan Keuangan, Promosi, dan lainnya yang dibuat khusus untuk toko retail di Melaka.SELENGKAPNYABrandKembangkan kebutuhan Brand dalam memantau keinginan pasar, menjaga harga di pasaran, serta analisis penjualan online menggunakan fitur yang dibuat khusus untuk para Brand di Melaka.SELENGKAPNYA' or . = 'Solusi Khusus untuk Setiap Tipe BisnisPercayakan operasional bisnis kamu dengan fitur-fitur yang menyesuaikan kebutuhan kamu dari Melaka ✨Penjual OnlineKelola berbagai toko marketplace kamu dari satu tempat dengan memanfaatkan fitur-fitur unggulan dari MelakaSELENGKAPNYAToko RetailTingkatkan efektivitas operasional bisnis dan penjualan di toko retail kamu menggunakan fitur Kasir, Catatan Keuangan, Promosi, dan lainnya yang dibuat khusus untuk toko retail di Melaka.SELENGKAPNYABrandKembangkan kebutuhan Brand dalam memantau keinginan pasar, menjaga harga di pasaran, serta analisis penjualan online menggunakan fitur yang dibuat khusus untuk para Brand di Melaka.SELENGKAPNYA')]</value>
      <webElementGuid>a14e2d0b-0c33-41d8-8293-706432b17257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
