<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(PT Melaka Commerce Technologies)_mobil_2f56e5</name>
   <tag></tag>
   <elementGuidId>5f2369c8-f72e-4f49-84fc-6234226fdd3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mobile-footer-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f']/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f4e834f5-e9fe-450d-8bb6-f1eb908a90cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/649bcd770cf4801a45688dd7_ic_mail.svg</value>
      <webElementGuid>61f88628-357d-42f7-bbd2-615f7495f2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2dd149b5-6ec7-471b-86b0-04b0e0b145db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Icon Whatsapp</value>
      <webElementGuid>ff64812a-1483-4dc9-a743-c659ec922e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-footer-icon</value>
      <webElementGuid>0f99dadd-08d0-4441-aeb2-4c3f14267942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f&quot;)/div[@class=&quot;div-block-9&quot;]/img[@class=&quot;mobile-footer-icon&quot;]</value>
      <webElementGuid>4f63c758-1c23-4f99-af99-f5d25e83f70b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f']/div[3]/img</value>
      <webElementGuid>6b813b4e-535f-4854-aec6-47af99bee093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Icon Whatsapp']</value>
      <webElementGuid>ab7b9530-4f32-45b5-99e8-68f1968d60d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/img</value>
      <webElementGuid>0aeb4995-df4b-44df-8150-93f12883e617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/649bcd770cf4801a45688dd7_ic_mail.svg' and @alt = 'Icon Whatsapp']</value>
      <webElementGuid>39cb8ea4-337a-496f-a6fa-83c741c72574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
