<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_helpmelaka.app_mobile-footer-icon</name>
   <tag></tag>
   <elementGuidId>ce7b28b0-4e99-4862-9d14-ed53a0dbad46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.div-block-10 > img.mobile-footer-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f']/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0f4e8da5-1d5f-4021-96f6-0d92739754ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/649bcd77df65ec0f63536112_ic_whatsapp.svg</value>
      <webElementGuid>a5dfc480-a8a9-4a85-920f-b03d18f619ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>eb5411e7-08fe-4f2d-9de7-8ad4ff31b1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Icon Email</value>
      <webElementGuid>cc761b4b-e764-4ef3-837f-f483e1eeb66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-footer-icon</value>
      <webElementGuid>cce02c74-1353-40ea-aa95-0f5f0e782dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f&quot;)/div[@class=&quot;div-block-10&quot;]/img[@class=&quot;mobile-footer-icon&quot;]</value>
      <webElementGuid>bfc3540a-8a92-4845-806a-ff065bdc218a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e8834e-c9e8833f']/div[2]/img</value>
      <webElementGuid>39b6988e-1277-4dd1-94d8-5876974d2778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Icon Email']</value>
      <webElementGuid>83472bfd-a37f-44c0-82d6-8d5d359fca8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/img</value>
      <webElementGuid>d0710c31-2732-4eb6-a367-eca9e21f28c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/649bcd77df65ec0f63536112_ic_whatsapp.svg' and @alt = 'Icon Email']</value>
      <webElementGuid>b95b3389-4e1b-4fd7-a1e1-6280b4915593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
