<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Solusi Khusus_image-71</name>
   <tag></tag>
   <elementGuidId>8894ee9b-74a3-4356-ba82-e75fd4ee91bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image-71</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='melaka-solution']/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8e866346-7c68-4373-8988-cdc3c63fc9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/6597b9511bc491c3012820b9_ic_user.png</value>
      <webElementGuid>0c000b7f-2353-411d-95bb-1edbc3c06c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>882a47ee-4b8b-47c4-8e79-e5d687eeb126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-71</value>
      <webElementGuid>7bbcd337-608d-40c1-a68e-32c83cf0f92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;melaka-solution&quot;)/div[@class=&quot;w-layout-vflex flex-block-17&quot;]/div[@class=&quot;w-layout-hflex flex-block-49&quot;]/div[@class=&quot;w-layout-hflex flex-block-16&quot;]/div[@class=&quot;business-type---card image-1&quot;]/div[@class=&quot;w-layout-hflex flex-block-48 image-71&quot;]/img[@class=&quot;image-71&quot;]</value>
      <webElementGuid>cdc29b3a-f6b3-4ff9-823c-84620d4f779e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='melaka-solution']/div/div/div/div/div/img</value>
      <webElementGuid>228e34e2-ada9-4285-9271-e1909723e4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/6597b9511bc491c3012820b9_ic_user.png')]</value>
      <webElementGuid>62f8ed38-4f56-4e94-b210-6fb954cbcf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>db8f5b01-585a-4f41-8ce7-96ec412c8338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/6597b9511bc491c3012820b9_ic_user.png']</value>
      <webElementGuid>dabecb3e-bd51-4546-a286-d71828406c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
