<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Belum ada data virtual BundlingTambah v_3705c1</name>
   <tag></tag>
   <elementGuidId>61b87810-87e7-409d-80d2-190cfe537b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg-neutral-N0.rounded-xl.p-6.flex.flex-col.items-center.gap-6.p-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8da5db6c-52f3-477d-ae54-602f6cf32c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-neutral-N0 rounded-xl p-6 flex flex-col items-center gap-6 p-10</value>
      <webElementGuid>d29ab21d-e83e-4152-b6cd-8ee0802acf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum ada data virtual BundlingTambah virtual bundling disini untuk kebutuhan toko kamu.TambahVirtual Bundling</value>
      <webElementGuid>e9505f91-da46-4ef5-93d4-3214a2df926b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[2]/div[@class=&quot;w-full&quot;]/div[@class=&quot;bg-neutral-N0 rounded-xl p-6 flex flex-col items-center gap-6 p-10&quot;]</value>
      <webElementGuid>4fbf8560-ae79-428a-9b8e-64adfa5b4387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]/div[2]/div</value>
      <webElementGuid>2db1d2e0-d54f-4e09-8f07-f82524d2902e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/following::div[2]</value>
      <webElementGuid>82547d2b-d464-4751-96a8-f9d5f48df5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div</value>
      <webElementGuid>775570df-0626-4087-a851-f110d1f962bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Belum ada data virtual BundlingTambah virtual bundling disini untuk kebutuhan toko kamu.TambahVirtual Bundling' or . = 'Belum ada data virtual BundlingTambah virtual bundling disini untuk kebutuhan toko kamu.TambahVirtual Bundling')]</value>
      <webElementGuid>3d510c86-b3a2-49e1-a7e6-4d22358f73a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
