<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tiktok Shop</name>
   <tag></tag>
   <elementGuidId>4baf8799-54a1-46c9-9d55-18c47e7579ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div/div[2]/div/div/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>326fb7df-ec68-499b-802c-dc26281df735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-neutral-N200 relative h-[90px] w-[96px] cursor-pointer rounded-xl border bg-white px-3 py-4 md:h-[150px] md:w-[140px]</value>
      <webElementGuid>2d1daad4-356b-429d-b65a-4bb3d502cf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>marketplace-option__div__marketplace-container</value>
      <webElementGuid>63db48fd-c1fc-4779-8884-2d4cf9adb216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiktok Shop</value>
      <webElementGuid>0f265c3b-0c57-4c59-a653-cf429c3e6f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[@class=&quot;flex flex-col gap-6&quot;]/div[@class=&quot;-mx-5 flex flex-col gap-4 bg-white p-4 md:mx-0 md:rounded-xl md:p-0&quot;]/div[1]/div[@class=&quot;md:p-6&quot;]/div[@class=&quot;flex flex-wrap justify-center gap-4 md:justify-start&quot;]/button[@class=&quot;border-neutral-N200 relative h-[90px] w-[96px] cursor-pointer rounded-xl border bg-white px-3 py-4 md:h-[150px] md:w-[140px]&quot;]</value>
      <webElementGuid>69d16686-1cac-4ebc-9d4b-fab0671d5bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div/div[2]/div/div/div/button[2]</value>
      <webElementGuid>9284f8b8-3089-4c7a-aa52-ab65ad5e3e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopee'])[1]/following::button[1]</value>
      <webElementGuid>d9f50388-d4a1-4a6f-8008-1ba8d4a5a87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamu bisa menambahkan hingga 5 toko online dalam 1 marketplace'])[1]/following::button[2]</value>
      <webElementGuid>aed15c80-ee98-4a53-b569-5e543161b717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokopedia'])[1]/preceding::button[1]</value>
      <webElementGuid>97650919-270f-46e5-ac2a-f52702e3fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>9249ca0e-4815-43e7-aa71-4a1d7aff903a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Tiktok Shop' or . = 'Tiktok Shop')]</value>
      <webElementGuid>533399e0-446e-48d1-8f18-228039b420b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
