<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hubungi CS Melaka di 6287777760336 untu_cfb01c</name>
   <tag></tag>
   <elementGuidId>e7e681d7-58a1-42c2-a24c-6eb4e88eb7a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b0a7524-a077-46bf-9196-a995cc552bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-row justify-center gap-2 pb-4 mt-[30px] flex md:mt-1 md:items-center</value>
      <webElementGuid>d99ef3f2-c5d1-496a-b26a-04bcb24c84b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hubungi CS Melaka di +6287777760336 untuk bantu koneksikan toko online Kamu.</value>
      <webElementGuid>dbace135-4df2-49a3-91b6-efca195081ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[@class=&quot;flex flex-col gap-6&quot;]/div[@class=&quot;-mx-5 flex flex-col gap-4 bg-white p-4 md:mx-0 md:rounded-xl md:p-0&quot;]/div[1]/div[@class=&quot;flex flex-col gap-4 px-4 md:gap-1&quot;]/div[@class=&quot;flex-row justify-center gap-2 pb-4 mt-[30px] flex md:mt-1 md:items-center&quot;]</value>
      <webElementGuid>803a4595-f717-4338-9ad4-a6ac92206efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>681df002-c387-42b2-b09c-62010817ea2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lazada'])[1]/following::div[2]</value>
      <webElementGuid>755fc83d-4db1-44c3-8cc7-b3c44f33bd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blibli'])[1]/following::div[5]</value>
      <webElementGuid>e780c5a0-84d9-4e52-8643-0f70c79058ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>feecd825-ecee-4e6e-a349-abcafd73ff9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hubungi CS Melaka di +6287777760336 untuk bantu koneksikan toko online Kamu.' or . = 'Hubungi CS Melaka di +6287777760336 untuk bantu koneksikan toko online Kamu.')]</value>
      <webElementGuid>046431c3-840c-49db-ab79-401f80680fa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
