<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Beranda</name>
   <tag></tag>
   <elementGuidId>329813cf-0871-4900-bfb3-916c0d600aab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/aside/div/nav/a/button/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.inline-flex.w-full.items-center.gap-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed163fef-9f14-46e4-90ed-c3d649bd31da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex w-full items-center gap-2</value>
      <webElementGuid>8f1c0ca7-83c2-4fb3-92e3-8d9ba2f72195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beranda</value>
      <webElementGuid>3e5fc87c-6058-4334-be5a-25c43447e78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;hidden md:block&quot;]/aside[@class=&quot;bg-neutral-N0 border-neutral-N200 z-10 min-h-screen border-r md:fixed md:inset-y-0 md:flex md:w-[248px] md:flex-col&quot;]/div[@class=&quot;flex flex-grow flex-col overflow-y-auto&quot;]/nav[@class=&quot;mr-2 flex flex-1 flex-col gap-1&quot;]/a[@class=&quot;group block w-full cursor-pointer overflow-hidden rounded-r-xl&quot;]/button[@class=&quot;w-full&quot;]/span[@class=&quot;flex min-h-[2.5rem] items-center gap-4 rounded group-hover:bg-blue-B100 bg-white gap-[10px] py-2 pr-2 pl-6&quot;]/span[@class=&quot;text-[0.875rem] font-normal leading-[1.25rem] tracking-[0.25px] w-full text-left text-he&quot;]/span[@class=&quot;inline-flex w-full items-center gap-2&quot;]</value>
      <webElementGuid>7caf00ae-b3d0-4565-8122-b0877369480c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/aside/div/nav/a/button/span/span/span</value>
      <webElementGuid>3e33c135-c307-488b-99ce-d6ce3f39ed42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwalkan Demo'])[1]/following::span[3]</value>
      <webElementGuid>4064c122-a91c-4de8-b42e-9ae1df0c43a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Saya'])[1]/preceding::span[1]</value>
      <webElementGuid>40ad4d6b-976f-4a5f-8f83-e9f075ece1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko Saya'])[1]/preceding::span[4]</value>
      <webElementGuid>ee4d489a-3650-47c3-aeec-0081ed821512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beranda']/parent::*</value>
      <webElementGuid>8f5d9302-9d50-4fb0-bfd0-1f687b8c1d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>813a872a-1e68-41be-8875-dfbe881f6e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Beranda' or . = 'Beranda')]</value>
      <webElementGuid>22ceb445-7dd1-4473-bdd7-40d6bc4116d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
