<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Impor Data OrderDemografis pelanggan ya_809319</name>
   <tag></tag>
   <elementGuidId>698d360e-64ac-46a2-b705-896feec83e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-panel-:rv:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5fffb2f-2834-4f83-a26b-faf8350b5a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col gap-6</value>
      <webElementGuid>0b3d7cbb-9663-4e8f-a42f-8e94d67f041f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>detail-promotion-tab__laporan</value>
      <webElementGuid>f9e4369b-dceb-4ae9-bd21-5e42a5a6b1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-panel-:rv:</value>
      <webElementGuid>d4428b6b-1d70-47af-8de3-bbd82112e9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
      <webElementGuid>ec0ca1e1-079a-40fd-9912-1933fe56c3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12b48f02-1ab9-4b8f-a90a-22c7204b878b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>8bc9949c-afc5-450b-89a8-592d18535eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:ru:</value>
      <webElementGuid>8e8df3ad-6660-4694-b07a-d32441f62fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Impor Data OrderDemografis pelanggan yang diolah dari data transaksimu.BACA LEBIH LANJUTBelum ada toko online terkoneksi, sambungkan toko online atau impor data order dari toko online Kamu.Koneksi Toko OnlineImpor Data Order</value>
      <webElementGuid>c7e08f57-9c25-46ea-8ff1-32ea8ef96cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:rv:&quot;)</value>
      <webElementGuid>8bc6a73b-bc17-413d-b574-7c23bfff1c39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:rv:']</value>
      <webElementGuid>10b9a961-6f35-4f8f-aba3-2c9faf3c1173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div/div[3]/div</value>
      <webElementGuid>77714ecf-66db-4e3c-bd72-0eb664292596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demografi Pelanggan'])[1]/following::div[2]</value>
      <webElementGuid>4c3fce86-5448-457e-b894-e775e17385db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impor Data Order'])[1]/following::div[4]</value>
      <webElementGuid>37718a4d-82cb-4cde-87b1-285c27b9cb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div</value>
      <webElementGuid>b9b111dd-b3ec-4bc6-8a63-6673a7e89a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-tabs-panel-:rv:' and (text() = 'Impor Data OrderDemografis pelanggan yang diolah dari data transaksimu.BACA LEBIH LANJUTBelum ada toko online terkoneksi, sambungkan toko online atau impor data order dari toko online Kamu.Koneksi Toko OnlineImpor Data Order' or . = 'Impor Data OrderDemografis pelanggan yang diolah dari data transaksimu.BACA LEBIH LANJUTBelum ada toko online terkoneksi, sambungkan toko online atau impor data order dari toko online Kamu.Koneksi Toko OnlineImpor Data Order')]</value>
      <webElementGuid>f64ac835-9907-4c24-9475-908f11018fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
