<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Riwayat transaksi belum tersediaJika ad_fc320f</name>
   <tag></tag>
   <elementGuidId>2588999b-5e88-4947-8186-3e1732c68646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[3]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46998175-236e-438d-81b5-e9fc1d4c86ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-neutral-N0 flex items-center justify-center px-5 py-4 md:p-10</value>
      <webElementGuid>834d61b1-235b-4f81-a4c2-e553d9062db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Riwayat transaksi belum tersediaJika ada pemasukan atau penarikan saldo aktif, maka akan ditampilkan disini.</value>
      <webElementGuid>c52f64b0-5a5e-40b6-b06b-85879274c99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[@class=&quot;md:bg-neutral-N0 flex flex-col gap-4 md:gap-0 md:rounded-xl&quot;]/div[2]/div[@class=&quot;bg-neutral-N0 flex items-center justify-center px-5 py-4 md:p-10&quot;]</value>
      <webElementGuid>db4e21bf-6844-43ee-a47d-f63f497a3527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[3]/div[2]/div[2]</value>
      <webElementGuid>2e1c1e1c-d9ac-4c07-ad18-4f08641ef27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Filter'])[2]/following::div[3]</value>
      <webElementGuid>31a4b3fd-8a69-45b4-809a-6f9ee077da20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Filter'])[1]/following::div[3]</value>
      <webElementGuid>003af84d-8b9c-4e87-875a-41dba3a0f784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]</value>
      <webElementGuid>b1275742-04df-4cb6-99d9-2cd8a9e1dd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Riwayat transaksi belum tersediaJika ada pemasukan atau penarikan saldo aktif, maka akan ditampilkan disini.' or . = 'Riwayat transaksi belum tersediaJika ada pemasukan atau penarikan saldo aktif, maka akan ditampilkan disini.')]</value>
      <webElementGuid>a85f5047-83e0-4278-8bd0-e4bec118055e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
