<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Setuju dan Lanjutkan</name>
   <tag></tag>
   <elementGuidId>b8a20f69-e1ce-48da-b233-5695e238ad51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ae38755-4c12-44ff-9a68-c002a61e6e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0055c3e-9e6f-44ce-80d5-0203c6a6d9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group relative inline-flex items-center justify-center gap-2 enabled:focus:outline-none text-disabled bg-neutral-N200 enabled:text-invert enabled:bg-blue-B700 enabled:hover:bg-blue-B600 enabled:focus:bg-blue-B600 py-3 px-6 rounded-xl block px-14</value>
      <webElementGuid>db61aeda-c7e2-4049-b7de-161a218585c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>journal-disclaimer-popup__button__agree</value>
      <webElementGuid>bcedf4ed-cb19-4365-bc15-51b11fde99ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48b06c0c-1a67-48a8-ba79-9acbf4d0aaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Setuju dan Lanjutkan</value>
      <webElementGuid>cda6a45a-9b0f-430f-b8ed-faa8b5376f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-:rm:&quot;)/div[@class=&quot;flex min-h-screen items-end justify-center text-center md:block md:p-0&quot;]/div[@class=&quot;relative inline-block h-screen w-full transform overflow-auto shadow-xl bg-white p-5 pt-4 text-left align-bottom transition-all md:my-8 md:h-auto md:w-full md:rounded-lg md:p-6 md:align-middle md:max-w-[600px] max-w-[552px]&quot;]/div[@class=&quot;flex flex-col gap-6&quot;]/button[@class=&quot;group relative inline-flex items-center justify-center gap-2 enabled:focus:outline-none text-disabled bg-neutral-N200 enabled:text-invert enabled:bg-blue-B700 enabled:hover:bg-blue-B600 enabled:focus:bg-blue-B600 py-3 px-6 rounded-xl block px-14&quot;]</value>
      <webElementGuid>c2b19673-f81c-467f-a6a4-eb40cd3ab2fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>85a72d84-e4d5-4eff-8869-03699a7ca2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:rm:']/div/div[2]/div/button</value>
      <webElementGuid>7257ccbf-623e-4f79-b86f-ee85dbe83fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Disclaimer hanya muncul sekali'])[1]/following::button[1]</value>
      <webElementGuid>ba8d4af3-2698-4c33-b1a1-e552cf5d4bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disclaimer'])[1]/following::button[1]</value>
      <webElementGuid>fd1f3505-142f-4bdc-aa63-62ae59e5aaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>4e6bfc2f-ce03-4b91-afdc-9285da6962ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Setuju dan Lanjutkan' or . = 'Setuju dan Lanjutkan')]</value>
      <webElementGuid>c096f8b1-ee4f-4002-903d-c2e024a39e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
