<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DisclaimerFitur catatan keuangan ini ha_ee9d75</name>
   <tag></tag>
   <elementGuidId>00c05236-4c22-4eb7-8ed4-2912ab0c8609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-:rm:']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a669c9e6-731f-4d47-a26f-d24a97672620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative inline-block h-screen w-full transform overflow-auto shadow-xl bg-white p-5 pt-4 text-left align-bottom transition-all md:my-8 md:h-auto md:w-full md:rounded-lg md:p-6 md:align-middle md:max-w-[600px] max-w-[552px]</value>
      <webElementGuid>404a0985-de8e-4c43-b232-775a6594926e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DisclaimerFitur catatan keuangan ini hanya menonjolkan beberapa aspek/perhitungan tertentu dari standar akuntansi sebagaimana diatur dalam Pernyataan Standar Akuntansi Keuangan (PSAK) / International Financial Reporting Standards (IFRS), dan mungkin tidak lengkap, benar, dan/atau komprehensif. Pengguna disarankan dengan tegas untuk tidak mengandalkan/mengacu kepada ringkasan/catatan keuangan ini, dan sangat disarankan untuk menghubungi penasihat profesional untuk mendapatkan layanan yang memadai dalam menghasilkan bentuk laporan keuangan yang dibakukan berdasarkan peraturan yang berlaku. Pengguna dengan ini menyatakan bahwa Pengguna akan menanggung sendiri serta membebaskan (Kami atau PT Melaka Commerce Technologies) dari segala risiko yang mungkin timbul dari penggunaan fitur catatan keuangan dan/atau catatan keuangan yang dihasilkan.*Disclaimer hanya muncul sekaliSetuju dan Lanjutkan</value>
      <webElementGuid>10c5aab2-9b7a-47d7-a922-92a5587d6c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-:rm:&quot;)/div[@class=&quot;flex min-h-screen items-end justify-center text-center md:block md:p-0&quot;]/div[@class=&quot;relative inline-block h-screen w-full transform overflow-auto shadow-xl bg-white p-5 pt-4 text-left align-bottom transition-all md:my-8 md:h-auto md:w-full md:rounded-lg md:p-6 md:align-middle md:max-w-[600px] max-w-[552px]&quot;]</value>
      <webElementGuid>961d0bec-2da5-4e19-8870-c83c6bcbf366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:rm:']/div/div[2]</value>
      <webElementGuid>1e2d2569-bdd8-484d-bb22-6e5d60ecb7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada catatan keuangan. Buat catatan keuanganmu disini'])[1]/following::div[13]</value>
      <webElementGuid>b524fdf4-e73e-4f52-b185-c150c0e0439d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Catatan'])[1]/following::div[14]</value>
      <webElementGuid>2de93a38-6178-4c55-a541-33877d5484e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>10e3311a-a59c-497d-9e93-ef2b512a37c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DisclaimerFitur catatan keuangan ini hanya menonjolkan beberapa aspek/perhitungan tertentu dari standar akuntansi sebagaimana diatur dalam Pernyataan Standar Akuntansi Keuangan (PSAK) / International Financial Reporting Standards (IFRS), dan mungkin tidak lengkap, benar, dan/atau komprehensif. Pengguna disarankan dengan tegas untuk tidak mengandalkan/mengacu kepada ringkasan/catatan keuangan ini, dan sangat disarankan untuk menghubungi penasihat profesional untuk mendapatkan layanan yang memadai dalam menghasilkan bentuk laporan keuangan yang dibakukan berdasarkan peraturan yang berlaku. Pengguna dengan ini menyatakan bahwa Pengguna akan menanggung sendiri serta membebaskan (Kami atau PT Melaka Commerce Technologies) dari segala risiko yang mungkin timbul dari penggunaan fitur catatan keuangan dan/atau catatan keuangan yang dihasilkan.*Disclaimer hanya muncul sekaliSetuju dan Lanjutkan' or . = 'DisclaimerFitur catatan keuangan ini hanya menonjolkan beberapa aspek/perhitungan tertentu dari standar akuntansi sebagaimana diatur dalam Pernyataan Standar Akuntansi Keuangan (PSAK) / International Financial Reporting Standards (IFRS), dan mungkin tidak lengkap, benar, dan/atau komprehensif. Pengguna disarankan dengan tegas untuk tidak mengandalkan/mengacu kepada ringkasan/catatan keuangan ini, dan sangat disarankan untuk menghubungi penasihat profesional untuk mendapatkan layanan yang memadai dalam menghasilkan bentuk laporan keuangan yang dibakukan berdasarkan peraturan yang berlaku. Pengguna dengan ini menyatakan bahwa Pengguna akan menanggung sendiri serta membebaskan (Kami atau PT Melaka Commerce Technologies) dari segala risiko yang mungkin timbul dari penggunaan fitur catatan keuangan dan/atau catatan keuangan yang dihasilkan.*Disclaimer hanya muncul sekaliSetuju dan Lanjutkan')]</value>
      <webElementGuid>173d3508-e483-4ac0-b6b1-464e368a6c70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
