<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Saat ini, kamu dapat menggunakan Melaka_af35f6</name>
   <tag></tag>
   <elementGuidId>e8aa683c-31ef-4f9b-8c2f-b51036f180e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='content'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>880bcaac-605a-44d4-8d37-c99a41e183c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>f66e2547-fd38-4a02-9ff4-cf09c176224b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>faq-1</value>
      <webElementGuid>94da4497-d417-4c12-8646-36140f407381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saat ini, kamu dapat menggunakan Melaka secara gratis dan tanpa ada biaya tersembunyi untuk menggunakannya. Ke depannya, Melaka akan menawarkan beberapa fitur tambahan yang mungkin akan membutuhkan biaya bulanan untuk menggunakannya. Tapi tenang saja, kami tidak akan menarik biaya bulanan tanpa persetujuan dari kamu ya!</value>
      <webElementGuid>0a74b512-b1dd-490a-a810-0c1b601924c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js w-mod-ix wf-nunito-i4-active wf-nunito-i5-active wf-nunito-i3-active wf-nunito-i2-active wf-nunito-i9-active wf-nunito-i6-active wf-nunito-i7-active wf-nunito-i8-active wf-nunito-n7-active wf-nunito-n4-active wf-nunito-n2-active wf-nunito-n8-active wf-nunito-n9-active wf-nunito-n6-active wf-nunito-n3-active wf-nunito-n5-active wf-active&quot;]/body[@class=&quot;body-4&quot;]/section[@class=&quot;page-content---faq-list&quot;]/div[@class=&quot;div---title-faq-list&quot;]/div[@class=&quot;div---faq-list&quot;]/div[@class=&quot;wrapper&quot;]/div[@id=&quot;content&quot;]</value>
      <webElementGuid>c8727f24-df7b-4679-bdf7-70d80e99e908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='content'])[4]</value>
      <webElementGuid>21bb2055-4c98-45ba-a5c7-d51c0ef3b9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah ada biaya yang perlu saya keluarkan untuk dapat menggunakan Melaka?'])[1]/following::div[1]</value>
      <webElementGuid>97b41916-8855-40dd-955d-91be83ad854d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://melaka.app/privacy-policy'])[1]/following::div[4]</value>
      <webElementGuid>061530a2-31ca-4abd-89ab-df132367a48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa yang perlu saya lakukan jika saya mengalami kendala dengan Melaka?'])[1]/preceding::div[1]</value>
      <webElementGuid>733cff06-2e29-4d22-a1fa-5b29e7209631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Bantuan Melaka'])[3]/preceding::div[3]</value>
      <webElementGuid>3b95f0e3-86a7-4733-8406-f55f4e122397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saat ini, kamu dapat menggunakan Melaka secara gratis dan tanpa ada biaya tersembunyi untuk menggunakannya. Ke depannya, Melaka akan menawarkan beberapa fitur tambahan yang mungkin akan membutuhkan biaya bulanan untuk menggunakannya. Tapi tenang saja, kami tidak akan menarik biaya bulanan tanpa persetujuan dari kamu ya!']/parent::*</value>
      <webElementGuid>c6a42b88-3858-4501-9420-6ccb9aaa4ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>e5deee6c-7fc3-4c07-9a45-ce0d5dda9965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'content' and (text() = 'Saat ini, kamu dapat menggunakan Melaka secara gratis dan tanpa ada biaya tersembunyi untuk menggunakannya. Ke depannya, Melaka akan menawarkan beberapa fitur tambahan yang mungkin akan membutuhkan biaya bulanan untuk menggunakannya. Tapi tenang saja, kami tidak akan menarik biaya bulanan tanpa persetujuan dari kamu ya!' or . = 'Saat ini, kamu dapat menggunakan Melaka secara gratis dan tanpa ada biaya tersembunyi untuk menggunakannya. Ke depannya, Melaka akan menawarkan beberapa fitur tambahan yang mungkin akan membutuhkan biaya bulanan untuk menggunakannya. Tapi tenang saja, kami tidak akan menarik biaya bulanan tanpa persetujuan dari kamu ya!')]</value>
      <webElementGuid>187804ad-af84-4a40-9cc3-7f2d1b2ed42b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
