<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pelajari Lebih Lanjut</name>
   <tag></tag>
   <elementGuidId>048a5a48-53a5-4cb2-aaaf-7bf4000643f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link-block.w-inline-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketplace-integration']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e401988-5c1d-4e12-86c0-659d1da5ad49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>analytics</name>
      <type>Main</type>
      <value>learn_more</value>
      <webElementGuid>ca78614b-79b9-4eb4-967c-844ad9b48a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text-link__marketplace-integration-more</value>
      <webElementGuid>973ab21a-6f47-41ad-80bf-d8631d0c9a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.melaka.app/help-center</value>
      <webElementGuid>a912332c-dea0-4e76-8b58-96c0a0190400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>36d4f6b4-3653-41c2-bf91-113ecbaa3622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-block w-inline-block</value>
      <webElementGuid>54b858ca-37fa-4bae-afa3-32b4d957bdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelajari Lebih Lanjut</value>
      <webElementGuid>19c3119e-5cb5-4788-928e-8127e5622a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-integration&quot;)/div[@class=&quot;flex-feature-texts&quot;]/a[@class=&quot;link-block w-inline-block&quot;]</value>
      <webElementGuid>619c5a2e-46b4-435f-bd7f-12d9a2b0178d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketplace-integration']/div[2]/a</value>
      <webElementGuid>9eb1e993-1f00-434a-9236-f75ba21460f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='banyak marketplace'])[1]/following::a[1]</value>
      <webElementGuid>30800d40-f24a-4f86-9545-56039b453433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANAJEMEN INVENTORI DAN ORDER'])[1]/preceding::a[1]</value>
      <webElementGuid>942ac9b9-0a8d-40d3-a458-9578adc25a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.melaka.app/help-center')]</value>
      <webElementGuid>40f00663-0bbe-4811-b647-93b6f149808e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a</value>
      <webElementGuid>ad787cd5-8643-452d-89d8-19d935e864cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.melaka.app/help-center' and (text() = 'Pelajari Lebih Lanjut' or . = 'Pelajari Lebih Lanjut')]</value>
      <webElementGuid>a46d564f-c25a-46c4-a159-e1ab298747b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
