<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INTEGRASI ANTAR MARKETPLACEPunya banyak_458566</name>
   <tag></tag>
   <elementGuidId>c0cdc769-7d43-478e-b560-63cd040df435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#marketplace-integration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketplace-integration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ad95ac12-825e-4b26-ab03-925c598f7357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marketplace-integration</value>
      <webElementGuid>87f41277-7cc8-4ef4-aec4-fe4fdbc42ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-feature</value>
      <webElementGuid>e86f8638-011e-49a7-afa1-24b98bf3bc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INTEGRASI ANTAR MARKETPLACEPunya banyak toko di banyak marketplace? Koneksikan aja duluDengan Melaka, kamu dapat memusatkan seluruh manajemen toko online-mu di berbagai marketplace hanya di satu platform saja.Pelajari Lebih Lanjut</value>
      <webElementGuid>f4cef79b-2fd4-465d-adf2-f7751848b183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-integration&quot;)</value>
      <webElementGuid>9127a282-a01e-46b0-9b5b-3c362bb1d243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='marketplace-integration']</value>
      <webElementGuid>06193504-5bbf-4705-b654-3afc0ec0b214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELENGKAPNYA'])[3]/following::div[2]</value>
      <webElementGuid>859e7763-552d-477a-b804-1ef22e14ac85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::div[4]</value>
      <webElementGuid>a96d6fec-dd8b-4e03-9fb2-05981585b11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>885cb390-3509-4311-974c-a51f6ef72f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'marketplace-integration' and (text() = 'INTEGRASI ANTAR MARKETPLACEPunya banyak toko di banyak marketplace? Koneksikan aja duluDengan Melaka, kamu dapat memusatkan seluruh manajemen toko online-mu di berbagai marketplace hanya di satu platform saja.Pelajari Lebih Lanjut' or . = 'INTEGRASI ANTAR MARKETPLACEPunya banyak toko di banyak marketplace? Koneksikan aja duluDengan Melaka, kamu dapat memusatkan seluruh manajemen toko online-mu di berbagai marketplace hanya di satu platform saja.Pelajari Lebih Lanjut')]</value>
      <webElementGuid>8f44d321-7cf1-42eb-a88a-e57e26c4955f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
