<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Selamat Datang di MelakaDaftarkan dirim_508182</name>
   <tag></tag>
   <elementGuidId>48ef0d04-3161-4698-a55c-977cc21b42d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b069521-5716-4688-ba7f-81a3cf61cb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-neutral-N0 z-10 col-span-1 grid pt-6 place-items-start justify-center content-start p-5 md:-mt-6 md:-ml-8 md:p-8 md:pl-0</value>
      <webElementGuid>39c5cc9c-9c06-46ff-9dbc-d201e498d1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selamat Datang di MelakaDaftarkan dirimu dan nikmati fitur-fitur terbaik dari Melaka untuk operasional bisnismu.NamaWajib diisi, min. 5 karakter.Nomor TeleponWajib diisi. Nomor telepon tidak boleh kurang dari 10 atau lebih dari 12 karakter.+62Nama Bisnis KamuWajib diisi.Tipe BisnisDistributorToko RetailBrandPenjual OnlineKebutuhan aplikasi dan performa sales, kelola inventori gudangEmailWajib diisi.IconKata SandiMin. 8 karakter, harus kombinasi dari huruf dan angka.IconKonfirmasi Kata SandiBaca dan setuju dengan syarat dan ketentuanDengan melanjutkan pendaftaran, kamu setuju dengan Syarat dan Ketentuan Melaka.DaftarSudah punya akun? Masuk disini.</value>
      <webElementGuid>e5df8ffd-696d-462b-af91-506b4d49bebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative flex min-h-screen flex-col&quot;]/div[@class=&quot;grid min-h-screen w-full grid-cols-1 md:grid-cols-2 mt-0 mb-8 md:mt-[49px]&quot;]/div[@class=&quot;bg-neutral-N0 z-10 col-span-1 grid pt-6 place-items-start justify-center content-start p-5 md:-mt-6 md:-ml-8 md:p-8 md:pl-0&quot;]</value>
      <webElementGuid>82262664-4867-424c-8e82-5d627fd5fcb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]</value>
      <webElementGuid>a8f9e44a-2676-4e89-b900-a3b49b1c7a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edukasi'])[1]/following::div[3]</value>
      <webElementGuid>64c50aaa-95bc-4e9f-8c24-e3534d458db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solusi Kami'])[1]/following::div[4]</value>
      <webElementGuid>9fb929f5-8eb7-4aab-b525-e92c52fc9534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>53f5d59d-a0eb-432e-9add-b37e574a85e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selamat Datang di MelakaDaftarkan dirimu dan nikmati fitur-fitur terbaik dari Melaka untuk operasional bisnismu.NamaWajib diisi, min. 5 karakter.Nomor TeleponWajib diisi. Nomor telepon tidak boleh kurang dari 10 atau lebih dari 12 karakter.+62Nama Bisnis KamuWajib diisi.Tipe BisnisDistributorToko RetailBrandPenjual OnlineKebutuhan aplikasi dan performa sales, kelola inventori gudangEmailWajib diisi.IconKata SandiMin. 8 karakter, harus kombinasi dari huruf dan angka.IconKonfirmasi Kata SandiBaca dan setuju dengan syarat dan ketentuanDengan melanjutkan pendaftaran, kamu setuju dengan Syarat dan Ketentuan Melaka.DaftarSudah punya akun? Masuk disini.' or . = 'Selamat Datang di MelakaDaftarkan dirimu dan nikmati fitur-fitur terbaik dari Melaka untuk operasional bisnismu.NamaWajib diisi, min. 5 karakter.Nomor TeleponWajib diisi. Nomor telepon tidak boleh kurang dari 10 atau lebih dari 12 karakter.+62Nama Bisnis KamuWajib diisi.Tipe BisnisDistributorToko RetailBrandPenjual OnlineKebutuhan aplikasi dan performa sales, kelola inventori gudangEmailWajib diisi.IconKata SandiMin. 8 karakter, harus kombinasi dari huruf dan angka.IconKonfirmasi Kata SandiBaca dan setuju dengan syarat dan ketentuanDengan melanjutkan pendaftaran, kamu setuju dengan Syarat dan Ketentuan Melaka.DaftarSudah punya akun? Masuk disini.')]</value>
      <webElementGuid>82dec50d-a8d4-4ac5-8b32-388e6560f5bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
