<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Kata Sandi_isTncChecked</name>
   <tag></tag>
   <elementGuidId>0a80219b-4a4c-4ed2-ad50-0ed89c2ce9e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register__checkbox__tnc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register__checkbox__tnc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>865f25c5-9bba-4128-ac61-8464a97fcb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>d9791170-fc6a-46e5-9fa6-384b74fc6845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>19619887-a74b-4470-8139-b493488a8569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isTncChecked</value>
      <webElementGuid>98612b1f-ee95-499c-a70b-9433c08c5ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7992a1cf-e8a3-441a-83cc-7183f4f87bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-blue-B700 border-neutral-N400 h-5 w-5 cursor-pointer rounded border-2 focus:outline-0 focus:ring-transparent disabled:text-neutral-N200 disabled:border-neutral-N200 disabled:cursor-not-allowed checked:disabled:text-blue-B400 checked:disabled:border-blue-B400 indeterminate:disabled:text-blue-B400 indeterminate:disabled:border-blue-B400</value>
      <webElementGuid>e4f5aec8-90ce-4e91-bb75-d1cc0f740ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>d3ff4ef2-e8b2-4a93-81f4-1cde9e620060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>329520c2-b054-4571-8f7b-0f5ced0bb5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register__checkbox__tnc&quot;)</value>
      <webElementGuid>98fd3c46-0940-4f54-92f2-7099ff09e1e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register__checkbox__tnc']</value>
      <webElementGuid>583a39f0-3e30-4e2c-a8a1-28c02671fb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[8]/div/input</value>
      <webElementGuid>e5de663d-a15a-4a8d-879b-5d21abc04d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>55a8c817-ac3e-4e46-b7bd-9b6fe5df4c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register__checkbox__tnc' and @name = 'isTncChecked' and @type = 'checkbox']</value>
      <webElementGuid>49dd94c7-37c7-49ab-be8e-f3a4b90118e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
