<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Belum Ada Data Catatan Piutang</name>
   <tag></tag>
   <elementGuidId>5e387410-79ed-405c-9c39-2f843480124a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.headline-h2.text-he</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>63f1240b-8235-4cbe-8c60-d848aa73494a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headline-h2 text-he</value>
      <webElementGuid>52a08469-ccd8-44f5-939a-71ecca91bc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>store-term-of-payment__no-data</value>
      <webElementGuid>b3eb746e-9306-4b53-98aa-afc5e843658f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum Ada Data Catatan Piutang</value>
      <webElementGuid>ab43e86a-2155-4e49-a076-193e77999201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[@class=&quot;flex flex-col items-center gap-3&quot;]/h2[@class=&quot;headline-h2 text-he&quot;]</value>
      <webElementGuid>fc791ca2-8545-47ac-aeba-0ffbb22a28f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div/h2</value>
      <webElementGuid>1d520792-57e1-4509-b0fc-16f9f40eb6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piutang'])[2]/following::h2[1]</value>
      <webElementGuid>9550cc6d-e1b9-4fb7-a645-3b2de1761853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::h2[1]</value>
      <webElementGuid>bee54c2f-fb49-4f4c-ad83-273d3fdfc4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belum Ada Data Catatan Piutang']/parent::*</value>
      <webElementGuid>f68f0045-e7b6-473e-9c8f-8be977ac4730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>daa2d8f6-0ebe-43e8-abc4-f2c0af683ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Belum Ada Data Catatan Piutang' or . = 'Belum Ada Data Catatan Piutang')]</value>
      <webElementGuid>9c824bea-d368-470d-b362-e0b63d3289c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
