<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Koleksi ProdukKoleksi Produk untuk dita_566581</name>
   <tag></tag>
   <elementGuidId>782e47c1-aa35-4f29-aa09-9c241195bf68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ac729f9-25b6-4b87-b53a-dfaa5c394394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col items-center justify-between gap-4 md:flex-row</value>
      <webElementGuid>2d28acf4-df2a-4ce3-90f9-628d6187dff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Koleksi ProdukKoleksi Produk untuk ditambahkan didaftar Katalog Melaka.TambahKoleksi Produk</value>
      <webElementGuid>1423029e-d004-48af-b3f9-eca5da5652d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-neutral-N100 flex min-h-screen flex-col&quot;]/div[@class=&quot;flex flex-1 flex-col md:pl-[248px]&quot;]/main[@class=&quot;relative flex min-h-full w-full flex-1 flex-col&quot;]/div[1]/div[4]/div[@class=&quot;bg-neutral-N100 min-h-full p-5 md:p-6 flex flex-1 flex-col gap-6&quot;]/div[@class=&quot;flex flex-col items-center justify-between gap-4 md:flex-row&quot;]</value>
      <webElementGuid>5e2c7e7d-7e31-48ea-8724-b8d1ded0156d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div[4]/div/div[2]</value>
      <webElementGuid>79c6607b-cfd5-4fb9-9fcf-4d25364ccb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koleksi Produk'])[2]/following::div[1]</value>
      <webElementGuid>ec9f9668-c70f-4257-8913-a85cf73ff118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk &amp; Stok'])[2]/following::div[1]</value>
      <webElementGuid>fcf96ba8-6d96-4993-8c77-7ed284f066d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>3d996ebf-406d-4423-820b-a719d1432fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Koleksi ProdukKoleksi Produk untuk ditambahkan didaftar Katalog Melaka.TambahKoleksi Produk' or . = 'Koleksi ProdukKoleksi Produk untuk ditambahkan didaftar Katalog Melaka.TambahKoleksi Produk')]</value>
      <webElementGuid>a5f1d7ae-e051-4a3e-b61a-fd91a4b8314b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
