<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nanti saja</name>
   <tag></tag>
   <elementGuidId>39b0b13a-f26f-46ed-a9a9-0d661ac81a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onesignal-slidedown-cancel-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onesignal-slidedown-cancel-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2739d104-b063-4d25-92b8-1eb7cf77cee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-right secondary slidedown-button</value>
      <webElementGuid>185206fb-4940-4de4-b341-7a2c37466545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-cancel-button</value>
      <webElementGuid>8a4a2ef8-2c18-4cd9-b5b6-e0cc502690a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nanti saja</value>
      <webElementGuid>b4d4a925-55a7-4c8b-b0d1-983b4ffade13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onesignal-slidedown-cancel-button&quot;)</value>
      <webElementGuid>37e66301-df09-451d-9878-4386ec83521c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onesignal-slidedown-cancel-button']</value>
      <webElementGuid>66b3269f-d491-4738-955d-8595e917efc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidedown-footer']/button[2]</value>
      <webElementGuid>78004341-a657-47f3-b9a9-de2587d7b8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya, Aktifkan'])[1]/following::button[1]</value>
      <webElementGuid>1521a105-6809-4978-852c-d83a2d8f062c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktifkan notifikasi untuk terus update pesanan baru dan pemberitahuan lainnya!'])[1]/following::button[2]</value>
      <webElementGuid>d79bb663-2c2b-4035-ba56-ec231f20461c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan Penggunaan'])[1]/preceding::button[1]</value>
      <webElementGuid>8c719889-ef3e-43a8-abf1-63f143067369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nanti saja']/parent::*</value>
      <webElementGuid>5c824049-cc55-40a0-ac93-9460181a25f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>f4e616ce-3572-4556-b10b-c5ba49593cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onesignal-slidedown-cancel-button' and (text() = 'Nanti saja' or . = 'Nanti saja')]</value>
      <webElementGuid>39073a8a-db2c-4e0f-a9e4-75bafe6b45cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
