<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aktifkan notifikasi untuk terus update _765753</name>
   <tag></tag>
   <elementGuidId>7132a6ee-93ed-4c29-8384-6d5657e88c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slidedown-body-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slidedown-body']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9001928f-da53-46b7-8b97-ef29e2b02c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slidedown-body-message</value>
      <webElementGuid>7a448394-f747-4ac6-9ec1-a1ee518c7717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktifkan notifikasi untuk terus update pesanan baru dan pemberitahuan lainnya!</value>
      <webElementGuid>75fb0c9f-61b3-4185-a4f3-71eec479eb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slidedown-body&quot;)/div[@class=&quot;slidedown-body-message&quot;]</value>
      <webElementGuid>11b59086-c346-4e90-8637-82b458506dbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidedown-body']/div[2]</value>
      <webElementGuid>583a26d0-ed05-40e0-894e-43ef5cdb4498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak ada data'])[1]/following::div[6]</value>
      <webElementGuid>9d80211b-49d2-4ca3-bac8-71fa217c0000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya, Aktifkan'])[1]/preceding::div[3]</value>
      <webElementGuid>fec709f5-6336-48a6-9289-fde0e58516d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nanti saja'])[1]/preceding::div[3]</value>
      <webElementGuid>286772ba-9222-441b-a014-dc5adfd4eade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktifkan notifikasi untuk terus update pesanan baru dan pemberitahuan lainnya!']/parent::*</value>
      <webElementGuid>79c49786-8785-4c10-9318-cc1016d485d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]</value>
      <webElementGuid>3dc72e87-8b92-4eff-bfca-9d08bb4feac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Aktifkan notifikasi untuk terus update pesanan baru dan pemberitahuan lainnya!' or . = 'Aktifkan notifikasi untuk terus update pesanan baru dan pemberitahuan lainnya!')]</value>
      <webElementGuid>d8f395e2-c2d1-4754-a8cc-aa13c8691246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
