<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pelajari Lebih Lanjut</name>
   <tag></tag>
   <elementGuidId>11717f4f-d59c-4bdc-9446-e230f4ccc406</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#store-management > div.flex-feature-texts > a.link-block.w-inline-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store-management']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10406288-321d-404d-95ce-ce4a83e154c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>analytics</name>
      <type>Main</type>
      <value>learn_more</value>
      <webElementGuid>77a5ae4e-a4ae-42ee-bf13-a6507d9ab271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text-link__store-management-more</value>
      <webElementGuid>06f07363-6a92-4c8b-aba2-caca983e1751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.melaka.app/help-center</value>
      <webElementGuid>060963f8-38f3-45d0-99aa-eb2b90aceaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>cc531e7c-e7d3-43c3-9647-60717dd6bb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-block w-inline-block</value>
      <webElementGuid>288293c5-029c-40e5-8504-d9f33b059ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelajari Lebih Lanjut</value>
      <webElementGuid>96be2506-6845-4e24-9505-c7fb1403f5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-management&quot;)/div[@class=&quot;flex-feature-texts&quot;]/a[@class=&quot;link-block w-inline-block&quot;]</value>
      <webElementGuid>a0632802-4ca4-4188-985f-276eff654826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store-management']/div/a</value>
      <webElementGuid>a7a68f3d-b736-47c4-997c-9c593b2def9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pesanan'])[1]/following::a[1]</value>
      <webElementGuid>6b7cc2a1-4fbd-4d18-a243-0d86c87954ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inventori'])[1]/following::a[1]</value>
      <webElementGuid>d7b54cb5-471a-4b7f-b5fa-67d503a8c020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOSI DAN ANALISIS PELANGGAN'])[1]/preceding::a[1]</value>
      <webElementGuid>30010ef6-92ff-4484-847d-16f3a56d3764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.melaka.app/help-center')])[2]</value>
      <webElementGuid>96bd5e65-ef14-43e2-be01-3b70a0b1bf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>188ca6a0-adce-4408-ad08-fe2716f7c424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.melaka.app/help-center' and (text() = 'Pelajari Lebih Lanjut' or . = 'Pelajari Lebih Lanjut')]</value>
      <webElementGuid>962ede2f-37a8-40aa-af16-012599dbd751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
