<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pelajari Lebih Lanjut</name>
   <tag></tag>
   <elementGuidId>790736d3-ba45-4a8d-ade2-07b6e2fe22ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#store-management > div.flex-feature-texts > a.link-block.w-inline-block > div.text-button---l</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store-management']/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c0d1bd1-69d0-4d8e-bda7-26f8e1d57329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-button---l</value>
      <webElementGuid>8b08fb60-bcec-4f7b-82b2-437753df6b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelajari Lebih Lanjut</value>
      <webElementGuid>8e544d4d-9d9a-441c-ad86-ce5146717f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-management&quot;)/div[@class=&quot;flex-feature-texts&quot;]/a[@class=&quot;link-block w-inline-block&quot;]/div[@class=&quot;text-button---l&quot;]</value>
      <webElementGuid>8876fd60-4424-4c24-b00b-7f113b25a48f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store-management']/div/a/div</value>
      <webElementGuid>4633d875-0c68-4f8f-ba72-b468dbedcba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pesanan'])[1]/following::div[2]</value>
      <webElementGuid>07fcbdb0-6e02-4e7b-b4ec-9fe70437894f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inventori'])[1]/following::div[2]</value>
      <webElementGuid>509026c0-5a75-46ac-9bf8-cff77b07ec4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOSI DAN ANALISIS PELANGGAN'])[1]/preceding::div[3]</value>
      <webElementGuid>210144b5-6d24-43eb-8e01-ad139da4bbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div</value>
      <webElementGuid>085f6fae-0546-4a41-9af3-f7fa65750303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pelajari Lebih Lanjut' or . = 'Pelajari Lebih Lanjut')]</value>
      <webElementGuid>68f804ad-350d-4445-8bd3-3da44644cb77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
