<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MANAJEMEN INVENTORI DAN ORDERAtur inven_23f353</name>
   <tag></tag>
   <elementGuidId>4f4908df-1023-4860-b97a-9c10099766f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#store-management</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store-management']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa7ae670-d3f2-425e-ac49-a400e0e2fe11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>store-management</value>
      <webElementGuid>84e613e0-ca08-4a07-85a2-793f373e4278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-feature</value>
      <webElementGuid>a08675e9-3edb-4dc1-ada2-32892e772235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut</value>
      <webElementGuid>223be612-7ae7-4241-8c5e-3dcb694baf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-management&quot;)</value>
      <webElementGuid>8aea8dbd-96f4-4262-98ee-b53c17b42144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='store-management']</value>
      <webElementGuid>231d68bd-a572-4a9d-beb8-df60e5cf48c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[1]/following::div[1]</value>
      <webElementGuid>6c0f0011-6b45-4f5c-80bd-6d3d85b12c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='banyak marketplace'])[1]/following::div[3]</value>
      <webElementGuid>6c3243c0-18ef-4fe7-942d-ad91b0e5d0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>8061bc84-0ba2-4802-86a1-566414f5c3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'store-management' and (text() = 'MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut' or . = 'MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut')]</value>
      <webElementGuid>b2e7cac3-9407-42df-ba19-10c7246b1416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
