<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MANAJEMEN INVENTORI DAN ORDERAtur inven_23f353_1</name>
   <tag></tag>
   <elementGuidId>d109e997-e800-4c48-901a-eded74d64b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#store-management > div.flex-feature-texts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store-management']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e10091fd-bb4a-4ebf-9ea1-08a28734eae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-feature-texts</value>
      <webElementGuid>3fb1dae3-9a36-4b5e-a2bc-8a04c23f4101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut</value>
      <webElementGuid>02c16482-cedb-4728-9cbd-62af03080b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-management&quot;)/div[@class=&quot;flex-feature-texts&quot;]</value>
      <webElementGuid>bde6348d-f9ba-46c5-bfa9-337374313acc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store-management']/div</value>
      <webElementGuid>a6e31183-b775-4f5c-8548-6fe3bccaae51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[1]/following::div[2]</value>
      <webElementGuid>92f3a86d-c69c-4b41-8e39-f01f1f6d11c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='banyak marketplace'])[1]/following::div[4]</value>
      <webElementGuid>9e04e906-84b3-496f-bc4a-076f28bf349f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>deee544b-23d8-4fce-bcad-ca9f9cad07ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut' or . = 'MANAJEMEN INVENTORI DAN ORDERAtur inventori dan pesanan toko online-mu dengan mudah dan terpusatKurangi resiko stok tidak sinkron atau pun pesanan lupa diproses karena repot mesti buka semua marketplace.Pelajari Lebih Lanjut')]</value>
      <webElementGuid>b249e30f-be6c-48e0-9056-0fa7115b368e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
