<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Toko Retail_businessType</name>
   <tag></tag>
   <elementGuidId>65df9971-39b7-419f-aca4-b5468a080617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='brand-:Re96l6:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05b1176a-6b94-4c80-b244-a434c982cc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>608a9098-2921-4f8e-b5c8-e9744499ff1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>20b43f16-d2d4-456d-bb2a-48d1cd5cb210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>brand-:Re96l6:</value>
      <webElementGuid>8bb5ddce-fe85-49b1-ab22-24f89782de4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-neutral-N400 enabled:checked:text-blue-B700 h-4 w-4 border-2 enabled:focus:ring-0 enabled:focus:ring-offset-0 disabled:bg-neutral-N100 disabled:cursor-not-allowed checked:disabled:bg-blue-B400 checked:disabled:hover:bg-blue-B400</value>
      <webElementGuid>09fa7847-416f-4662-8c2d-969b4614a87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__radio-button__brand</value>
      <webElementGuid>bb66d401-50a5-4070-8e2a-0e21efcd7d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>a4846b92-0423-4084-836d-c82ff0ce1d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brand-:Re96l6:&quot;)</value>
      <webElementGuid>5dd18ffe-83be-4267-a7a3-c660e5e0cb3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='brand-:Re96l6:']</value>
      <webElementGuid>7bd0a343-d77e-4b23-a2d2-e998f84b4b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[4]/div[2]/div[3]/input</value>
      <webElementGuid>918b8798-8903-4556-9940-303df2ee8b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a741deb9-77c6-4798-b4c1-93024e734839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'businessType' and @id = 'brand-:Re96l6:']</value>
      <webElementGuid>779b2e9a-cc4c-47ad-bb2e-68b85d0e6e48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
