<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tipe Bisnis_businessType</name>
   <tag></tag>
   <elementGuidId>1dcce844-4158-4729-a36a-9fa1d83d486b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='distributor-:R696l6:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e814160a-1e04-4ac4-bca6-5eab8600a2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6284ee7d-a397-4c5d-9e1d-aeffa47ccbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>6b55b856-5ef9-4326-acac-4d0c3ad42a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>distributor-:R696l6:</value>
      <webElementGuid>834a5945-4229-4a99-ac71-829e8111e417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-neutral-N400 enabled:checked:text-blue-B700 h-4 w-4 border-2 enabled:focus:ring-0 enabled:focus:ring-offset-0 disabled:bg-neutral-N100 disabled:cursor-not-allowed checked:disabled:bg-blue-B400 checked:disabled:hover:bg-blue-B400</value>
      <webElementGuid>1a214154-6c18-4d1e-ac9f-4e420585abec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__radio-button__distributor</value>
      <webElementGuid>a44668c4-be1d-4677-b4ba-8c5dc047695a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>distributor</value>
      <webElementGuid>cf77dd8c-f1e0-4dd1-ab41-50b3dcb34959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;distributor-:R696l6:&quot;)</value>
      <webElementGuid>4d326802-64cc-4ba9-9ebd-eb8220e01296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='distributor-:R696l6:']</value>
      <webElementGuid>6e6b1616-18d2-4a12-9b49-438b9b931d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[4]/div[2]/div/input</value>
      <webElementGuid>08a28bfc-4e25-4d11-bfc9-66374e109ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>72fef9ff-8691-42e9-8642-5b330c1a76d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'businessType' and @id = 'distributor-:R696l6:']</value>
      <webElementGuid>3cc79217-c551-4383-8881-8cb60c96e5bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
