<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Setuju</name>
   <tag></tag>
   <elementGuidId>04ff54eb-2171-478d-84a7-ddf3bfe9207c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.uf-button.uf-button-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b08f0353-9910-4abd-a7e0-7d66f309fe60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21ae6053-288b-4606-81fa-56484541612a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uf-button uf-button-primary</value>
      <webElementGuid>5febfba1-d7be-4f6d-92b8-34d8480261fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>d6a3440a-a5f6-4677-9cbd-e2b9d7b61be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Setuju</value>
      <webElementGuid>39e8ceb6-c67e-4a12-973b-ab19b39331e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u-banner-018ba7c7-e939-8053-5261-f399cae36fd4&quot;)/div[@class=&quot;uf-bannerInner uf-bannerInner--left&quot;]/div[@class=&quot;uf-bannerActions&quot;]/div[@class=&quot;uf-actions left&quot;]/button[@class=&quot;uf-button uf-button-primary&quot;]</value>
      <webElementGuid>35be0518-d24e-452f-9149-f28bc3f50f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>219301ce-5d85-4f4a-9ea0-45621adfcafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u-banner-018ba7c7-e939-8053-5261-f399cae36fd4']/div/div[2]/div/button</value>
      <webElementGuid>bfd2d791-9870-46f8-996e-f5ed0ee6154e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::button[1]</value>
      <webElementGuid>20c7752d-025d-45e5-8e31-495848f8c5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan Penggunaan'])[1]/following::button[1]</value>
      <webElementGuid>2d54f96f-0825-4cd1-b88f-c1b3f12d7951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Setuju']/parent::*</value>
      <webElementGuid>12696973-cdb6-43bf-be80-66b12083ca76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f478fad9-1d33-41b8-aed5-c846774244f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Setuju' or . = 'Setuju')]</value>
      <webElementGuid>e44f7c2b-0900-4e29-8ccc-b6b382f23685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
