<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kelola hasil penjualan di semua bisnis _2f0e4e</name>
   <tag></tag>
   <elementGuidId>bce51a93-badf-4ca2-8f80-96389a5d328b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accounting > div.flex-feature-texts > div.h1.he.h1-mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accounting']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>32509008-5569-4578-bb64-3684cb5569cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text__accounting-content</value>
      <webElementGuid>8d351889-4d48-4284-9bb6-75d645f00d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1 he h1-mobile</value>
      <webElementGuid>cdcc89a1-a130-4b6f-9c77-ea61643400ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelola hasil penjualan di semua bisnis online dan toko kamu dengan mudah</value>
      <webElementGuid>6e45751a-8228-4188-9918-ec38d3708161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accounting&quot;)/div[@class=&quot;flex-feature-texts&quot;]/div[@class=&quot;h1 he h1-mobile&quot;]</value>
      <webElementGuid>2750bfda-ecb3-4257-bdbd-62dbc2938bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accounting']/div/div[2]</value>
      <webElementGuid>df3fdab3-b6f6-42c0-8cde-e5010b4aaed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATATAN KEUANGAN'])[1]/following::div[1]</value>
      <webElementGuid>c1657612-2fee-45e6-931a-ec953f11f271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[3]/following::div[4]</value>
      <webElementGuid>a5d6ce7a-2548-4afe-a479-1d92bfbce6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[4]/preceding::div[2]</value>
      <webElementGuid>3c24c08f-dc5b-47de-91b4-982857d45552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelola']/parent::*</value>
      <webElementGuid>73e256c6-496f-4cb5-995f-5dc1885a3d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div[2]</value>
      <webElementGuid>db987569-d5dd-4935-aeaa-b8380e754647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kelola hasil penjualan di semua bisnis online dan toko kamu dengan mudah' or . = 'Kelola hasil penjualan di semua bisnis online dan toko kamu dengan mudah')]</value>
      <webElementGuid>8ae6e5c3-86ab-488d-8a79-2a8d5d058e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
