<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Solusi Melaka</name>
   <tag></tag>
   <elementGuidId>e6d19229-2571-4a8f-bb40-08f3cafbd61d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w-dropdown-toggle-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-dropdown-toggle-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>68bb8c95-db8a-4484-b5e1-8bd96137e8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navdropdown sol-ed w-dropdown-toggle</value>
      <webElementGuid>76087261-a3fc-4b68-9b2c-218955c8a69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w-dropdown-toggle-0</value>
      <webElementGuid>5604503f-de46-4d80-bb2b-5bc0ad5263f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>w-dropdown-list-0</value>
      <webElementGuid>9234dddc-4957-4564-a828-0da7255a1094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>0972349e-4853-4f05-95b0-a90a60f97d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58a3e1dc-10b7-4f5f-88e5-91dbac9ac917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>327777cd-46ac-42d6-8373-05b226c2ce5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e39ab8b-279f-4db4-abb9-c9eb51886d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solusi Melaka</value>
      <webElementGuid>d75c1b56-a919-457c-b822-2320c423d43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-dropdown-toggle-0&quot;)</value>
      <webElementGuid>09e76a69-1531-42b2-b2f6-ed86e869cbfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='w-dropdown-toggle-0']</value>
      <webElementGuid>5c526687-22e6-4bdf-b04f-30340ffc93fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integrasi Marketplace'])[1]/preceding::div[3]</value>
      <webElementGuid>1ab8ba62-a470-4eb0-8489-b0e07bb19efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/div</value>
      <webElementGuid>17878768-3634-43e8-a919-b44e70dbbfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'w-dropdown-toggle-0' and (text() = 'Solusi Melaka' or . = 'Solusi Melaka')]</value>
      <webElementGuid>bebc2427-40c6-4c26-8cd9-e4d52a1e6bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
