<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terdaftar di</name>
   <tag></tag>
   <elementGuidId>f315431c-82fc-4d41-8d31-caaa9c756ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5774b5a-adfb-4eb0-b919-88854c202193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f</value>
      <webElementGuid>b1d0c93f-f393-43d5-a35a-a24cb8850ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-layout-cell cell-8</value>
      <webElementGuid>aa73ac56-0785-4de4-8e0e-9d15f2ec457c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terdaftar di</value>
      <webElementGuid>6acb41eb-7a0c-41cf-aac1-492e049043f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f&quot;)</value>
      <webElementGuid>ee6e7a4b-824d-44ca-ab98-1fa133eb561d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f']</value>
      <webElementGuid>f61c5658-760f-46e3-974f-3b004e103be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88342-c9e8833f']/div[4]</value>
      <webElementGuid>760b16c8-6201-4b09-a560-d6c4d3bcf06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='help@melaka.app'])[1]/following::div[5]</value>
      <webElementGuid>70443a44-0681-4acf-8e83-c14520c1d3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(PT Melaka Commerce Technologies)'])[1]/following::div[7]</value>
      <webElementGuid>628f2002-f8d7-4cd2-bff7-62a068eb2b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solusi Kami'])[1]/preceding::div[2]</value>
      <webElementGuid>4cd532ed-d339-4d29-a5d2-d7845482a7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]</value>
      <webElementGuid>16aef7c8-ae73-4480-b09f-fbbeb49ca5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f' and (text() = 'Terdaftar di' or . = 'Terdaftar di')]</value>
      <webElementGuid>70342a5b-ffdb-4f51-bd52-a8995fb0a936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
