<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INTEGRASI ANTAR MARKETPLACE</name>
   <tag></tag>
   <elementGuidId>e62053e2-5a2c-48eb-b538-f4127bbd7a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.b2.le.margin-bot-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketplace-integration']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7327bcc9-37ab-4b71-b0f6-a179270b5ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text__marketplace-integration-title</value>
      <webElementGuid>e09fb4b9-4d85-47a8-92ba-b207fba76934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b2 le margin-bot-12</value>
      <webElementGuid>4e2802c5-691f-4a3c-96df-544740e81923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INTEGRASI ANTAR MARKETPLACE</value>
      <webElementGuid>64104e53-6ca8-4c88-b127-d493f492147e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-integration&quot;)/div[@class=&quot;flex-feature-texts&quot;]/div[@class=&quot;b2 le margin-bot-12&quot;]</value>
      <webElementGuid>044ac9f4-27c9-4501-bc88-81e5c6395e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketplace-integration']/div[2]/div</value>
      <webElementGuid>6c67f8d4-a718-4538-b8b2-8282c75cf421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELENGKAPNYA'])[3]/following::div[5]</value>
      <webElementGuid>e3b76919-4fe3-4110-acf7-38058a920d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/following::div[7]</value>
      <webElementGuid>769f43eb-4287-4390-b5e0-b74f1a2fe36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='banyak marketplace'])[1]/preceding::div[1]</value>
      <webElementGuid>d44c8287-a193-471e-adc3-cea59ff1869f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INTEGRASI ANTAR MARKETPLACE']/parent::*</value>
      <webElementGuid>2e9a80c3-87ca-4334-84fd-bc4539df4dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div</value>
      <webElementGuid>773ac439-9229-457d-905e-436f788612cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'INTEGRASI ANTAR MARKETPLACE' or . = 'INTEGRASI ANTAR MARKETPLACE')]</value>
      <webElementGuid>fc5a83d0-8f32-4d65-89f2-bf9eaea173fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
