<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_helpmelaka.app</name>
   <tag></tag>
   <elementGuidId>5c19f16d-edec-4cd4-87af-3cca294cb0df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.b1.mobile-footer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f03cd24b-e781-4988-b6db-4166a9a2afd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing__text__email</value>
      <webElementGuid>c0bdb7bf-4cc3-448f-834a-ac8bae165f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b1 mobile-footer</value>
      <webElementGuid>a35514f8-dfcc-486e-872e-b3c984563544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>help@melaka.app</value>
      <webElementGuid>b0bb4c9d-f3fb-43cf-8bec-2bfc90aa1743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f&quot;)/div[@class=&quot;div-block-9&quot;]/div[@class=&quot;b1 mobile-footer&quot;]</value>
      <webElementGuid>1815a6a4-f708-4e48-8656-c52782e8c521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88345-c9e8833f']/div[3]/div</value>
      <webElementGuid>fdbe208f-e2e4-4112-84c9-5c247457db3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(PT Melaka Commerce Technologies)'])[1]/following::div[2]</value>
      <webElementGuid>f9b775fa-9384-4e98-a6c1-668619be1d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Pengaduan Konsumen dan Masyarakat'])[1]/following::div[3]</value>
      <webElementGuid>126ecd3f-aaf0-40e0-af59-7d709783775e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terdaftar di'])[1]/preceding::div[5]</value>
      <webElementGuid>7fe8f76c-8e46-4b64-94a7-5106ad1f9d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solusi Kami'])[1]/preceding::div[7]</value>
      <webElementGuid>db5c6746-672e-422f-8c1a-749057e231fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='help@melaka.app']/parent::*</value>
      <webElementGuid>8b12cad7-6f80-4d8c-919e-dc63eb59e51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>b0db4adb-d40a-4b66-b3f0-4f5ae5f7dc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'help@melaka.app' or . = 'help@melaka.app')]</value>
      <webElementGuid>7415ae50-f7a7-477c-92c1-7414032d8910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
