<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bikin promosi yang tepat gak bingung ka_2b35e5</name>
   <tag></tag>
   <elementGuidId>4ddd4d95-261f-419e-a80e-f97d7cca09b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promotion > div.flex-feature-texts > div.h1.he.h1-mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotion']/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d765fd53-c77a-48a9-98cf-16f0f5364ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>landing-feature__text__promotion-content</value>
      <webElementGuid>ec3eaf0f-8ce5-485c-b2e8-8e4687bd1f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1 he h1-mobile</value>
      <webElementGuid>cea26f23-1a9b-4a28-b3d7-2680b3720bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bikin promosi yang tepat gak bingung kalau tahu targetnya!</value>
      <webElementGuid>fff71092-d1de-4c75-8cef-2a6df013477a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotion&quot;)/div[@class=&quot;flex-feature-texts&quot;]/div[@class=&quot;h1 he h1-mobile&quot;]</value>
      <webElementGuid>11116924-da71-4a1d-a6c0-733b024e9c5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotion']/div[2]/div[2]</value>
      <webElementGuid>62599dfb-fcbf-42c3-bb8e-019b3483deee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOSI DAN ANALISIS PELANGGAN'])[1]/following::div[1]</value>
      <webElementGuid>4e7fab8e-5bba-4176-8b74-443ba65374d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[2]/following::div[6]</value>
      <webElementGuid>f024f8ee-11f0-42c6-8226-8bf2fe514ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bikin']/parent::*</value>
      <webElementGuid>422dc9b9-4fea-4cd2-8380-426cc1898f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div[2]</value>
      <webElementGuid>52fec293-6807-4fc4-8d66-5ba9c15cde2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bikin promosi yang tepat gak bingung kalau tahu targetnya!' or . = 'Bikin promosi yang tepat gak bingung kalau tahu targetnya!')]</value>
      <webElementGuid>2635255b-c5c1-4563-ad4b-3182638d1c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
