<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PROMOSI DAN ANALISIS PELANGGANBikin pro_17f7b1</name>
   <tag></tag>
   <elementGuidId>90ddf358-f06b-4105-aa23-f82eafe1148c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promotion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5ecc949-d8d2-4d6a-b978-a838e87e289b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promotion</value>
      <webElementGuid>a8c9043a-e66f-46df-a3b1-e91e1e59b1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-feature image-align-left</value>
      <webElementGuid>fa9899ac-602a-4c7d-affa-802a8604fd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROMOSI DAN ANALISIS PELANGGANBikin promosi yang tepat gak bingung kalau tahu targetnya!Maksimalkan keuntungan dari promosi yang kamu buat dengan mengetahui target pasarmu supaya promosimu tepat sasaran.Pelajari Lebih Lanjut</value>
      <webElementGuid>d593110e-a86e-4783-8ab6-8823617df3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotion&quot;)</value>
      <webElementGuid>a344b820-6d78-457e-bb80-96cc122969d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='promotion']</value>
      <webElementGuid>edd7d77f-d108-4e71-af3c-ed211e7f6800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Lebih Lanjut'])[2]/following::div[2]</value>
      <webElementGuid>542eb7ea-0aee-4b9d-8f9b-60f3de84db26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pesanan'])[1]/following::div[4]</value>
      <webElementGuid>bd222593-9feb-4d24-8d8d-802a9f43add4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>60225f0b-bf2c-49e3-b921-22f71c632847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'promotion' and (text() = 'PROMOSI DAN ANALISIS PELANGGANBikin promosi yang tepat gak bingung kalau tahu targetnya!Maksimalkan keuntungan dari promosi yang kamu buat dengan mengetahui target pasarmu supaya promosimu tepat sasaran.Pelajari Lebih Lanjut' or . = 'PROMOSI DAN ANALISIS PELANGGANBikin promosi yang tepat gak bingung kalau tahu targetnya!Maksimalkan keuntungan dari promosi yang kamu buat dengan mengetahui target pasarmu supaya promosimu tepat sasaran.Pelajari Lebih Lanjut')]</value>
      <webElementGuid>10e79701-af08-41e1-987f-01bd5c8dfa3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
