<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Solusi Khusus untuk Setiap Tipe Bisnis</name>
   <tag></tag>
   <elementGuidId>7739c6d3-7c03-4dd9-8db3-3a121bd99351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.heading-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='melaka-solution']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>264555b5-24ed-442c-b064-107b45a38d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-12</value>
      <webElementGuid>93a274bc-86bd-4ec8-b1c5-bea15e39021c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solusi Khusus untuk Setiap Tipe Bisnis</value>
      <webElementGuid>8650d2ec-d5e6-47cb-8c98-c8cf4128da84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;melaka-solution&quot;)/div[@class=&quot;w-layout-vflex flex-block-17&quot;]/h1[@class=&quot;heading-12&quot;]</value>
      <webElementGuid>c9d049ab-2190-4a8d-bb65-a32fc289fa3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='melaka-solution']/div/h1</value>
      <webElementGuid>ae9a236d-a1e3-4314-8ee9-ce6a8b26fb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelajari Selengkapnya'])[1]/following::h1[1]</value>
      <webElementGuid>debaa7c3-a986-4bd5-a8e2-b1152f7239c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MULAI GUNAKAN, GRATIS!'])[1]/following::h1[1]</value>
      <webElementGuid>78e82c5f-4698-4639-96e3-06c8a5a2a610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjual Online'])[1]/preceding::h1[1]</value>
      <webElementGuid>65e8e9a2-2ae5-42d2-8abc-600442d568cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='untuk Setiap Tipe Bisnis']/parent::*</value>
      <webElementGuid>9886691e-9873-4b1e-87ca-cebf8e7c3d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h1</value>
      <webElementGuid>ee607044-a3fa-4fb8-b6cd-f0812832b637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Solusi Khusus untuk Setiap Tipe Bisnis' or . = 'Solusi Khusus untuk Setiap Tipe Bisnis')]</value>
      <webElementGuid>387e698c-1c48-4716-9a15-3b570e7d67ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
