<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>0e20e90c-3b2b-48d7-8293-2d4dd69c5ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Icon Melaka&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88343-c9e8833f']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f51f02ab-3631-4958-9c98-db7581270545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/650177139726dbc3248818ad_melaka%20new.png</value>
      <webElementGuid>cb7a5f47-200c-49b0-a131-fdbf0a2782bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f0572f4c-4dfc-4553-b7a2-497a4bd5de2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>11e2d039-575f-4793-b098-83047426f298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>5b5b3aa0-d081-427c-84eb-404d50b1cc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Icon Melaka</value>
      <webElementGuid>f8e8abb5-daf0-47b9-8158-b1a0b4c89202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e88343-c9e8833f&quot;)/img[1]</value>
      <webElementGuid>6396083d-02e0-4914-8b65-a63a3ce8ecc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88343-c9e8833f']/img</value>
      <webElementGuid>ed81cf55-e36b-4009-8683-834c7aa2e288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Icon Melaka']</value>
      <webElementGuid>ed935152-27e8-4ce8-a2e1-9556d5739d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/img</value>
      <webElementGuid>f4e2d98d-205c-49e6-afd5-b31bc7c6f877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/650177139726dbc3248818ad_melaka%20new.png' and @alt = 'Icon Melaka']</value>
      <webElementGuid>58839b4d-d845-4487-b4bc-c2b2d6d9afe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
