<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>d727ead0-6f2a-43d1-a4fc-642039057771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Icon Sosmed IG&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Icon Sosmed IG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f08d0e4-4292-4ec9-8cf3-8929890bb4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0f314a54-fe1a-42d2-8e04-2668105b1c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Icon Sosmed IG</value>
      <webElementGuid>4b02b61c-ad80-4060-bc1e-90b84739e6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/649bcf140a168622b0b96be2_ic_instagram.svg</value>
      <webElementGuid>291937f6-9788-4b49-b37c-69f1d42a6744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js w-mod-ix wf-nunito-n2-active wf-nunito-n5-active wf-nunito-n3-active wf-nunito-n9-active wf-nunito-n8-active wf-nunito-n4-active wf-nunito-n6-active wf-nunito-n7-active wf-nunito-i3-active wf-nunito-i4-active wf-nunito-i8-active wf-nunito-i7-active wf-nunito-i9-active wf-nunito-i6-active wf-nunito-i5-active wf-nunito-i2-active wf-active&quot;]/body[1]/div[@class=&quot;container-footer-new&quot;]/div[@class=&quot;div-block-15&quot;]/div[@class=&quot;footer-right footer-mobile&quot;]/div[@class=&quot;div-block-14&quot;]/a[@class=&quot;link-block-5 w-inline-block&quot;]/img[1]</value>
      <webElementGuid>f745a67d-fcd0-4b28-bf34-6461476d41eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Icon Sosmed IG']</value>
      <webElementGuid>b725c3a2-6256-4247-8e9e-9615a539a105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/img</value>
      <webElementGuid>a04788ed-15ab-4572-a62a-04947aefc2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Icon Sosmed IG' and @src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/649bcf140a168622b0b96be2_ic_instagram.svg']</value>
      <webElementGuid>eb8b835c-90f2-4fb3-9b5f-bfdcb6a5ccd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
