<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SELENGKAPNYA_image-51_1</name>
   <tag></tag>
   <elementGuidId>2a105add-44be-43bf-a6b5-64df488ac17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='melaka-solution']/div/div/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0ad21bfa-d09a-4b15-ad6e-0f7e64f4eb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/659e4a72c0fc21b599c3a3d5_brand-card.png</value>
      <webElementGuid>f3815f7c-ef10-46f2-9ee9-b5bd047a0fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>872e03be-b304-4bd9-82c1-1c9fbac82b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 479px) 100vw, (max-width: 767px) 89vw, (max-width: 991px) 91vw, (max-width: 1439px) 75vw, 1074.1640625px</value>
      <webElementGuid>5a333750-36d9-4886-b3ab-7cd7c0b4ec5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/659e4a72c0fc21b599c3a3d5_brand-card-p-500.png 500w, https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/659e4a72c0fc21b599c3a3d5_brand-card-p-800.png 800w, https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/659e4a72c0fc21b599c3a3d5_brand-card.png 1000w</value>
      <webElementGuid>81e95ff6-456f-4da4-93e8-77053abb0884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-51</value>
      <webElementGuid>0bfbcc84-7677-4898-98dc-3f8525362719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;melaka-solution&quot;)/div[@class=&quot;w-layout-vflex flex-block-17&quot;]/div[@class=&quot;w-layout-hflex flex-block-49&quot;]/div[@class=&quot;w-layout-hflex flex-block-16&quot;]/div[@class=&quot;business-type---card image-2&quot;]/img[@class=&quot;image-51&quot;]</value>
      <webElementGuid>9ac0edd5-cda0-46f5-bfd1-28ebc13ebd97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='melaka-solution']/div/div/div/div[3]/img</value>
      <webElementGuid>69c971cb-2d5b-4bf0-8aa5-377885f72bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/659e4a72c0fc21b599c3a3d5_brand-card.png')]</value>
      <webElementGuid>7b017da0-79a6-4b07-8ebe-e3315cb325da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/img</value>
      <webElementGuid>fd4cd004-29fa-47e5-a9f1-7b0d9ffec73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/659e4a72c0fc21b599c3a3d5_brand-card.png']</value>
      <webElementGuid>c8667980-c4c0-4d50-b590-7bfd02d1806a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
