<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Terdaftar di_image-6</name>
   <tag></tag>
   <elementGuidId>ab065a88-000b-43ed-ac57-6c4a0fda6cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c3bf788-fb1d-40f1-aaa7-8b68e7975283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/64a5231179c7365967b9e0dd_kominfo-crop.png</value>
      <webElementGuid>5a769dd1-ec16-4b43-9620-f1f10a29656c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5bd61074-20e8-4433-9403-9d805c59e896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>61</value>
      <webElementGuid>2cf8a60d-51c9-4e20-a400-234e00765c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Icon Keminfo</value>
      <webElementGuid>4903e0b1-4d50-4284-aefc-add9bbeaf7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-6</value>
      <webElementGuid>0ca3f06e-c7ba-42ed-b3b1-bb8a4cceec76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f&quot;)/img[@class=&quot;image-6&quot;]</value>
      <webElementGuid>b705a570-0a6b-4f94-b8a1-da3f3e89b915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-node-_6588967d-e133-fa01-338b-edbac9e88357-c9e8833f']/img</value>
      <webElementGuid>b6834512-564f-4bdd-bffe-3693eeceb7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Icon Keminfo']</value>
      <webElementGuid>e9e14da6-7047-44df-b148-6796e644bb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/img</value>
      <webElementGuid>a2a814d6-0e35-4d35-a84a-72f8132b12ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/64a5231179c7365967b9e0dd_kominfo-crop.png' and @alt = 'Icon Keminfo']</value>
      <webElementGuid>6fbb9d2e-e06f-4af5-a264-9dc747d126b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
