<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SELENGKAPNYA_image-71</name>
   <tag></tag>
   <elementGuidId>d02f5aed-6c4b-4db9-8035-2776782b4822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.business-type---card.image-2 > div.w-layout-hflex.flex-block-48.image-71 > img.image-71</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='melaka-solution']/div/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c978c86-08a2-4eb6-88a0-08bb005d2c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/6597b9a36bf8b6c1c865b520_ic_marketplace.png</value>
      <webElementGuid>fe5c8a21-a22e-44b9-99cc-ff92c37d238b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>04441295-7635-430a-aa92-294a81422bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-71</value>
      <webElementGuid>71872ab5-47a6-4d1a-afd6-aa4aece475ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;melaka-solution&quot;)/div[@class=&quot;w-layout-vflex flex-block-17&quot;]/div[@class=&quot;w-layout-hflex flex-block-49&quot;]/div[@class=&quot;w-layout-hflex flex-block-16&quot;]/div[@class=&quot;business-type---card image-2&quot;]/div[@class=&quot;w-layout-hflex flex-block-48 image-71&quot;]/img[@class=&quot;image-71&quot;]</value>
      <webElementGuid>bf1dd0f0-200d-4083-ac1d-586db8a33b88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='melaka-solution']/div/div/div/div[2]/div/img</value>
      <webElementGuid>25aeda05-fe4a-4c5f-ba12-1d209c252489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/6597b9a36bf8b6c1c865b520_ic_marketplace.png')]</value>
      <webElementGuid>8f9d7331-f36d-4f24-bc6d-b7f74bb9a66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>98c6e4a2-9f0f-4885-b6e0-ed24aab00977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.prod.website-files.com/648a8a601ca0200e7d511b40/6597b9a36bf8b6c1c865b520_ic_marketplace.png']</value>
      <webElementGuid>7a6cdf76-3c6b-4af1-a95e-a504722a6b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
